import Foundation
import SwiftUI
import Combine

// MARK: - AppLanguage Enum
enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case german = "de"
    case english = "en"
    case polish = "pl"
    case czech = "cs"
    case turkish = "tr"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .german:    return "Deutsch"
        case .english:   return "English"
        case .polish:    return "Polski"
        case .czech:     return "Čeština"
        case .turkish:   return "Türkçe"
        }
    }

    var flag: String {
        switch self {
        case .german:    return "🇩🇪"
        case .english:   return "🇬🇧"
        case .polish:    return "🇵🇱"
        case .czech:     return "🇨🇿"
        case .turkish:   return "🇹🇷"
        }
    }
}

// MARK: - LocalizationManager
class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    @Published var language: AppLanguage

    init() {
        // iOS-Systemsprache verwenden; Fallback auf Deutsch
        let preferred = Locale.preferredLanguages.first.flatMap { tag in
            AppLanguage(rawValue: String(tag.prefix(2)))
        } ?? .german
        self.language = preferred
    }

    func t(_ key: String) -> String {
        return translations[language]?[key] ?? translations[.german]?[key] ?? key
    }
}

// MARK: - Global localization function
func L(_ key: String) -> String {
    return LocalizationManager.shared.t(key)
}

// MARK: - Translations Dictionary
let translations: [AppLanguage: [String: String]] = [
    .german: [
        // Actions
        "action.add": "Hinzufügen",
        "action.edit": "Bearbeiten",
        "action.delete": "Löschen",
        "action.cancel": "Abbrechen",
        "action.save": "Speichern",
        "action.done": "Fertig",
        "action.close": "Schließen",

        // Common
        "common.optional": "Optional",
        "common.note": "Notiz",
        "common.date": "Datum",
        "common.amount": "Betrag",
        "common.region": "Region",

        // Tabs (Tab Bar)
        "tab.trips": "Fahrten",
        "tab.meals": "Verpflegung",
        "tab.accommodation": "Übernachtung",
        "tab.vehicle": "Fahrzeug",
        "tab.overview": "Übersicht",
        "tab.fahrten": "Fahrzeit",
        "tab.arbeitszeit": "Verpflegung",
        "tab.uebernachtung": "Übernacht.",
        "tab.kfz": "KFZ",
        "tab.statistik": "Statistik",
        "tab.search": "Suche",

        // TravelRegion
        "region.inland": "Inland",
        "region.schweiz": "Schweiz",
        "region.ausland": "Ausland",

        // HotelMode
        "hotel.mode.flat": "Pauschale",
        "hotel.mode.actual": "Tatsächlicher Betrag",

        // VehicleCostCategory
        "vehicle.cat.werkstatt": "Werkstatt / Reparatur",
        "vehicle.cat.versicherung": "Versicherung",
        "vehicle.cat.tuev": "TÜV / HU",
        "vehicle.cat.steuer": "KFZ-Steuer",
        "vehicle.cat.reifen": "Reifen",
        "vehicle.cat.leasing": "Leasing",
        "vehicle.cat.strom": "Strom / Laden",
        "vehicle.cat.waesche": "Fahrzeugwäsche",
        "vehicle.cat.sonstiges": "Sonstiges",

        // ReisespesenKategorie
        "kfz.cat.werkstatt": "Werkstatt",
        "kfz.cat.leasing": "Leasing",
        "kfz.cat.vignette": "Vignette / Maut",
        "kfz.cat.benzin": "Benzin",
        "kfz.cat.strom": "Strom / Laden",
        "kfz.cat.steuer": "KFZ-Steuer",
        "kfz.cat.versicherung": "KFZ-Versicherung",
        "kfz.cat.verpflegung": "Verpflegung",
        "kfz.cat.sonstiges": "Sonstiges",

        // KFZ view strings
        "kfz.title": "KFZ Kosten",
        "kfz.belege": "Belege",
        "kfz.manual": "Manuell erfassen",
        "kfz.scan": "Beleg scannen",
        "kfz.scan.hint": "Kamera oder Foto – Daten werden automatisch erkannt",
        "kfz.empty.title": "KFZ Kosten",
        "kfz.empty.subtitle": "Werkstatt, Leasing, Benzin und weitere Kosten erfassen",
        "kfz.empty.scan": "Scannen",
        "kfz.empty.manual": "Manuell",
        "kfz.kategorie": "Kategorie",
        "kfz.betrag": "Betrag",
        "kfz.notiz": "Notiz",
        "kfz.bezeichnung": "Bezeichnung",
        "kfz.add.first": "Ersten Eintrag hinzufügen",
        "kfz.ausgaben": "Ausgaben",
        "kfz.netto": "Netto",
        "kfz.waesche.title": "Fahrzeugwäsche",
        "kfz.waesche.hint": "Tippe auf + um eine Fahrzeugwäsche zu erfassen.",
        "kfz.waesche.gesamt": "Gesamt",
        "kfz.standard.kwh": "Ø Standardwert übernehmen (0,30 €/kWh)",

        // Overview
        "overview.empty.title": "Keine Daten",
        "overview.empty.subtitle": "Erfasse Fahrten, Verpflegung oder\nÜbernachtungen",
        "overview.total": "Gesamterstattung",
        "overview.trips.unit": "Fahrten",
        "overview.days.unit": "Tage",
        "overview.nights.unit": "Nächte",
        "overview.accommodation.short": "Übernacht.",

        // Trips
        "trips.gps.tile": "GPS starten",
        "trips.gps.menu": "GPS-Aufzeichnung",
        "trips.new.tile": "Neue\nFahrt",
        "trips.empty.title": "Keine Fahrten",
        "trips.empty.subtitle": "Starte eine GPS-Aufzeichnung oder füge eine Fahrt manuell hinzu",
        "trips.all": "Alle Fahrten",
        "trips.unit": "Fahrt(en)",
        "trips.form.new": "Neue Fahrt",
        "trips.form.edit": "Fahrt bearbeiten",
        "trips.from": "Von",
        "trips.to": "Nach",
        "trips.km.label": "Kilometer",
        "trips.result": "Ergebnis",
        "trips.distance": "Strecke",
        "trips.rate": "Pauschale",
        "trips.reimbursement": "Erstattung",
        "trips.start": "Startort",
        "trips.destination": "Zielort",
        "trips.route": "Route",
        "trips.navigation.section": "Navigation",
        "trips.calculation": "Berechnung",
        "trips.maps.title": "Maps-Integration",
        "trips.maps.subtitle": "Automatische Routenberechnung · nur in Pro",
        "trips.maps.open": "Navigation öffnen mit",
        "trips.apple.maps": "Apple Karten",
        "trips.google.maps": "Google Maps",
        "trips.maps.open.btn": "In Maps öffnen",
        "trips.auto.label": "Automatisch",
        "trips.auto.hint": "Start und Ziel eingeben – km werden automatisch eingetragen",
        "trips.auto.calc": "Wird automatisch berechnet…",
        "trips.route.computing": "Route wird automatisch berechnet…",
        "trips.route.error": "Bitte Start- und Zielort prüfen",
        "trips.live.route": "Live-Route",
        "trips.gps.title": "GPS-Fahrt",
        "trips.gps.heading": "GPS-Fahrt aufzeichnen",
        "trips.gps.desc": "Die gefahrene Strecke wird per GPS gemessen\nund automatisch übertragen.",
        "trips.gps.startbtn": "Aufzeichnung starten",
        "trips.gps.running": "Aufzeichnung läuft",
        "trips.gps.stop": "Fahrt beenden & übertragen",
        "trips.gps.permission": "Standortberechtigung wird angefragt…",
        "trips.gps.permission.desc": "Bitte erlaube den Standortzugriff im Dialog.",
        "trips.gps.geocoding": "Adressen werden ermittelt…",
        "trips.gps.geocoding.wait": "Einen Moment bitte",
        "trips.gps.detected": "GPS-Fahrt erkannt",
        "trips.gps.detected.desc": "Strecke, Start und Ziel wurden automatisch ermittelt. Bitte prüfen und ggf. korrigieren.",
        "trips.gps.waiting": "Warte auf GPS…",
        "trips.nav.start": "Navigation starten",

        // Meals
        "meals.add": "Verpflegung hinzufügen",
        "meals.add.hint": "Tippe um einen Tag hinzuzufügen",
        "meals.all": "Alle Einträge",
        "meals.unit": "Tag(e)",
        "meals.form.new": "Neue Verpflegung",
        "meals.form.edit": "Eintrag bearbeiten",
        "meals.region": "Reiseregion",
        "meals.absence": "Arbeitszeit gesamt",
        "meals.begin": "Beginn",
        "meals.end": "Ende",
        "meals.result": "Ergebnis",
        "meals.absence.label": "Arbeitszeit",
        "meals.level": "Stufe",
        "meals.allowance": "Verpflegungspauschale",
        "meals.badge.none": "Keine",
        "meals.level.none": "Keine (< 1 h)",
        "meals.level.1": "Stufe 1 (1–3 h)",
        "meals.level.2": "Stufe 2 (3–6 h)",
        "meals.level.3": "Stufe 3 (ab 6 h)",

        // Accommodation
        "hotel.title": "Übernachtungen",
        "hotel.add": "Übernachtung hinzufügen",
        "hotel.add.hint": "Tippe um eine Übernachtung hinzuzufügen",
        "hotel.all": "Alle Übernachtungen",
        "hotel.unit": "Nacht/Nächte",
        "hotel.section": "Übernachtung",
        "hotel.form.new": "Neue Übernachtung",
        "hotel.form.edit": "Übernachtung bearbeiten",
        "hotel.city": "Stadt / Ort",
        "hotel.city.placeholder": "z.B. Berlin",
        "hotel.name": "Hotel",
        "hotel.billing": "Abrechnungsart",
        "hotel.type": "Art",
        "hotel.cost": "Betrag (€)",
        "hotel.reimbursement": "Erstattung",
        "hotel.flat.label": "Übernachtungspauschale",
        "hotel.actual.cost": "Tatsächliche Kosten",
        "hotel.flat.badge": "Pauschale",
        "hotel.actual.badge": "Ist-Betrag",
        "hotel.info": "Pauschale %@ / Nacht. Übersteigen die tatsächlichen Kosten die Pauschale, wird der volle Betrag erstattet.",
        "hotel.over.flat": "Über Pauschale (%@)",

        // Vehicle
        "vehicle.title": "Fahrzeugkosten",
        "vehicle.add": "Fahrzeugkosten hinzufügen",
        "vehicle.add.hint": "Werkstatt, Versicherung oder andere KFZ-Kosten",
        "vehicle.unit": "Eintrag/Einträge",
        "vehicle.form.new": "Neue Kosten",
        "vehicle.form.edit": "Kosten bearbeiten",
        "vehicle.category.section": "Kategorie",
        "vehicle.details": "Details",
        "vehicle.title.label": "Bezeichnung",
        "vehicle.mileage": "Kilometerstand (km)",
        "vehicle.summary": "Zusammenfassung",

        // Navigation titles
        "nav.arbeitszeit": "Verpflegung & Spesen",
        "nav.kfz": "KFZ Kosten",
        "nav.search": "Suche",
        "nav.uebernachtung": "Übernachtungen",
        "nav.trips": "Fahrten",

        // Misc
        "misc.today": "Heute",
        "misc.details": "Details",
        "misc.date": "Datum",
        "misc.optional": "Optional",
        "misc.no.entries": "Keine Einträge",
        "misc.no.entries.period": "Keine Einträge im gewählten Zeitraum",
        "misc.trip.end": "Fahrt beenden",
        "misc.edit": "Bearbeiten",
        "misc.new": "Neu",
        "misc.all.trips": "Alle Fahrten",
        "misc.copy": "Kopieren",
        "misc.send": "Senden",
        "misc.manage": "Verwalten",
        "misc.stop": "Stoppen",
        "misc.resume": "Jetzt fortsetzen",
        "misc.end.trip": "Fahrt beenden",
        "misc.recorded.so.far": "aufgezeichnet bisher",
        "misc.paused": "Pausiert",
        "misc.loading": "Wird geladen…",
        "misc.private": "Privat",
        "misc.business": "Geschäftlich",
        "misc.no.entries.search": "Keine Einträge gefunden",
        "misc.search.hint": "Tippe einen Begriff ein oder\nwähle ein Datum",
        "misc.search.hint2": "Versuche einen anderen Suchbegriff\noder ein anderes Datum",

        // Filter chips (Arbeitszeit / Fahrten)
        "filter.day": "Tag",
        "filter.week": "Woche",
        "filter.month": "Monat",
        "filter.all": "Alle",
        "filter.year": "Jahr",

        // Arbeitszeit
        "arbeitszeit.add.title": "Arbeitstag erfassen",
        "arbeitszeit.add.subtitle": "Gesamtarbeitszeit und Verpflegungspauschale erfassen",
        "arbeitszeit.no.entries": "Keine Einträge im gewählten Zeitraum",
        "arbeitszeit.monteur": "Monteurszulage (Lohn, separat)",
        "arbeitszeit.wochenende": "Wochenend-/Feiertagszulage (Lohn, separat)",

        // Settings
        "settings.title": "Einstellungen",
        "settings.km.title": "Kilometererstattung",
        "settings.km.rate": "Km-Pauschale",
        "settings.km.footer": "Steuerlicher Höchstsatz 2026: 0,38 € / km für Pkw",
        "settings.meals.title": "Verpflegungspauschalen",
        "settings.meals.footer": "Alle Beträge frei konfigurierbar. Pauschalen unter 1 h Abwesenheit sind immer 0 €.",
        "settings.hotel.footer": "Standard Deutschland: 20,00 € / Nacht (§ 9 Abs. 1 Nr. 5a EStG). Grenzgänger mit Schweizer Arbeitgeber und Tätigkeit in Deutschland: bitte individuell prüfen. Individuelle Beträge können frei eingetragen werden.",
        "settings.hours.1to3": "1 – 3 Stunden",
        "settings.hours.3to6": "3 – 6 Stunden",
        "settings.hours.6plus": "Ab 6 Stunden",
        "settings.reset": "Auf Standardwerte zurücksetzen",
        "settings.diagnosis": "Diagnose",
        "settings.feedback": "Feedback & Support",
        "settings.log": "Fehlerprotokoll",
        "settings.info": "Info & Rechtliches",
        "settings.privacy": "Datenschutz",
        "settings.help": "App Features & Hilfe",
        "settings.imprint": "Impressum",
        "settings.language": "Sprache",
        "settings.language.section": "App-Sprache",
        "settings.log.empty": "Keine Einträge.",
        "settings.log.clear": "Protokoll löschen?",
        "settings.gps.carplay": "GPS bei CarPlay-Verbindung starten",
        "settings.gps.carplay.footer": "Startet die GPS-Aufzeichnung automatisch, sobald dein iPhone mit CarPlay verbunden wird.",
        "settings.home.address": "Heimatadresse",
        "settings.home.footer": "Wird im Fahrtenformular als Schnellzugriff-Button (🏠) angezeigt und in der Fahrtenliste markiert.",
        "settings.km.label": "Kilometerpauschale",
        "settings.km.legal.footer": "Gesetzlicher Standardwert: 0,38 € / km (§ 9 Abs. 1 Nr. 4a EStG, seit Januar 2026)",
        "settings.chf.rate": "Kurs (EUR = … CHF)",
        "settings.region.inland": "Inland",
        "settings.region.schweiz": "Schweiz (in CHF)",
        "settings.region.ausland": "Ausland",
        "settings.meals.values.footer": "Inland: 0 € · 14 € · 28 €  |  Schweiz: 0 · 65 · 65 CHF  |  Ausland: 0 € · 10 € · 35 €",
        "settings.mechanic.allowance": "Monteurszulage",
        "settings.weekend.allowance": "Wochenend-/Feiertagszulage",
        "settings.hotel.title": "Übernachtung/Frühstück",
        "settings.hotel.flat": "Übernachtungspauschale",
        "settings.hotel.breakfast": "Frühstückspauschale",
        "settings.fuel.type": "Antrieb / Kraftstoffart",
        "settings.fuel.label": "Antrieb / Kraftstoff",
        "settings.fuel.consumption.kwh": "Verbrauch (kWh/100 km)",
        "settings.fuel.consumption": "Durchschnittsverbrauch",
        "settings.fuel.price.electricity": "Standard-Strompreis",
        "settings.fuel.price": "Standard-Spritpreis",
        "settings.privacy.label": "Datenschutzerklärung",
        "settings.help.label": "App-Funktionen & Anleitung",
        "settings.mechanic.inland.label": "Zulage Inland / Deutschland",
        "settings.mechanic.swiss.label": "Zulage Schweiz / Außerhalb des Werks",
        "settings.mechanic.abroad.label": "Zulage Ausland / Außerhalb des Werks und Deutschlands",
        "settings.weekend.inland.label": "Zulage Inland / Europa",
        "settings.weekend.swiss.label": "Zulage Schweiz / Europa",
        "settings.weekend.abroad.label": "Zulage Ausland / Übrige Gebiete",
        "settings.mechanic.footer": "Pauschale Zulage: 12 \u{20AC} Inland, 18 CHF Schweiz, 50 \u{20AC} Ausland. Wird über den Lohn ausbezahlt, NICHT Teil der Erstattung.",
        "settings.weekend.footer": "Pauschale Tageszulage Inland/Schweiz (60 € / 90 CHF) oder Ausland (72 €). Gilt Sa/So oder Feiertagen. Über den Lohn ausbezahlt, NICHT Teil der Erstattung.",
        "settings.fuel.footer": "Antriebsart, Preis und Verbrauch werden beim Anlegen neuer Fahrten automatisch vorausgefüllt. Leer = manuelle Eingabe pro Fahrt.",
        "settings.reset.footer": "Stellt alle gesetzlichen Standardwerte gemäß § 9 Abs. 4a EStG wieder her.",
        "settings.reset.confirm": "Alle Pauschalsätze werden auf die gesetzlichen Standardwerte zurückgesetzt.",
        "settings.backup": "Backup & Wiederherstellen",
        "settings.backup.save.local": "Backup lokal speichern",
        "settings.backup.share": "Backup teilen / in Cloud exportieren",
        "settings.backup.restore": "Backup wiederherstellen",
        "settings.backup.saved": "Gespeicherte Backups",
        "settings.backup.footer": "'Lokal speichern' legt das Backup in der Dateien-App ab. 'Teilen' ermöglicht Export in iCloud Drive, Google Drive oder per AirDrop. Max. 10 Backups werden aufbewahrt.",
        "settings.delete.all": "Alle Einträge löschen",
        "settings.delete.footer": "Löscht unwiderruflich alle Einträge. Einstellungen bleiben erhalten.",
        "settings.manage.data": "Daten verwalten",
        "settings.app.info": "App Info und Datenschutz",
        "settings.version": "App Version",
        "settings.developer": "Entwickler",
        "settings.contact": "Kontakt",
        "settings.log.section": "Protokoll & Feedback",
        "settings.log.title": "App-Protokoll",
        "settings.log.empty.desc": "Das Protokoll ist leer.",
        "settings.log.show": "Protokoll anzeigen",
        "settings.swipe.actions": "Legt fest welche Aktion und Farbe beim Wischen nach links oder rechts erscheint.",
        "settings.swipe.delete": "Löschen",
        "settings.swipe.edit": "Bearbeiten",
        "settings.swipe.copy": "Kopieren",
        "settings.swipe.none": "-",
        "settings.swipe.title": "Wischgesten",
        "settings.swipe.left": "Swipe links",
        "settings.swipe.right1": "Swipe rechts 1",
        "settings.swipe.right2": "Swipe rechts 2",
        "settings.accessibility": "Bedienungshilfen",
        "settings.log.delete": "Protokoll löschen",
        "settings.log.delete.title": "Protokoll löschen?",
        "settings.log.delete.msg": "Das Protokoll wird geleert. Es wird beim nächsten App-Start automatisch neu angelegt.",
        "settings.log.deleted": "Protokoll gelöscht.",
        "settings.log.mem.note": "Das Protokoll wird nur im Arbeitsspeicher geführt und beim nächsten App-Start automatisch geleert. Es enthält keine personenbezogenen Daten.",
        "settings.language.footer": "Die App verwendet die iOS-Systemsprache. Zum Ändern: Einstellungen → Allgemein → Sprache & Region → iPhone-Sprache.",
        "settings.delete.confirm": "Diese Aktion kann nicht rückgängig gemacht werden. Erstelle vorher ein Backup.",
        "settings.restore.confirm": "Alle aktuellen Daten werden durch die Backup-Daten ersetzt.",
        "settings.delete.all.title": "Alle Einträge löschen?",
        "settings.delete.all.btn": "Alles löschen",
        "settings.all.deleted": "Alle Einträge wurden gelöscht.",
        "settings.restore.title": "Backup wiederherstellen?",
        "settings.restore.btn": "Backup laden",
        "settings.reset.title": "Standardwerte wiederherstellen?",
        "settings.reset.btn": "Zurücksetzen",
        "settings.backup.loading": "Lade Backups…",
        "settings.backup.empty.title": "Noch keine iCloud Backups",
        "settings.backup.empty.hint": "Erstelle ein Backup über Einstellungen → iCloud Backup",
        "settings.backup.saved.title": "Gespeicherte Backups",
        "settings.backup.restore.btn": "Wiederherstellen",
        "settings.backup.restore.msg": "Alle aktuellen Daten werden durch das Backup vom %@ ersetzt.",
        "settings.backup.delete.title": "Backup löschen?",
        "settings.scan.receipt": "Beleg scannen",
        "settings.scan.receipt.hint": "Positionen, Kategorien und Beträge automatisch erkennen",
        "settings.entry.add": "Eintrag hinzufügen",

        // Overview
        "overview.ausgaben": "Ausgaben",
        "overview.not.reimbursable": "nicht erstattungsfähig",
        "overview.total.ausgaben": "Gesamtausgaben",
        "overview.meal.balance": "Verpflegung Saldo",
        "overview.flat.label": "Pauschale",
        "overview.fuel": "Kraftstoff / Strom",
        "overview.driven.km": "Kosten gefahrener km",
        "overview.meal.expenses": "Verpflegungsausgaben",
        "overview.travel.expenses": "Reisespesen / KFZ",
        "overview.private.expenses": "Private Ausgaben",
        "overview.entry": "Eintrag",
        "overview.entries": "Einträge",
        "overview.no.entries": "Keine Einträge",

        // Filter
        "filter.woche": "Woche",
        "filter.monat": "Monat",
        "filter.jahr": "Jahr",

        // Statistik
        "stat.tab.months": "Monate",
        "stat.tab.routes": "Strecken",
        "stat.tab.tax": "Steuer",
        "stat.reimbursement.per.month": "Erstattung pro Monat",
        "stat.best.month": "Bester Monat: **%@** mit %@",
        "stat.top.routes": "Häufigste Strecken",
        "stat.tax.year": "Steuerjahr %@",
        "stat.total.reimbursement": "Gesamterstattung %@",
        "stat.tax.annex.n": "Für Anlage N / Reisekostenabrechnung",
        "stat.mechanic.allowance": "Monteurszulage %@",
        "stat.payroll.note": "Lohnbestandteil – nicht Teil der Reisekosten (Anlage N)",
        "stat.disclaimer": "Diese Auswertung dient als Orientierung. Bitte prüfe die Beträge mit deinem Steuerberater oder Steuerprogramm.",

        // Summary tiles (Jahresübersicht)
        "stat.trips.label": "Fahrten",
        "stat.km.label": "Kilometer",
        "stat.reimbursement.label": "Erstattung",
    ],

    .english: [
        // Actions
        "action.add": "Add",
        "action.edit": "Edit",
        "action.delete": "Delete",
        "action.cancel": "Cancel",
        "action.save": "Save",
        "action.done": "Done",
        "action.close": "Close",

        // Common
        "common.optional": "Optional",
        "common.note": "Note",
        "common.date": "Date",
        "common.amount": "Amount",
        "common.region": "Region",

        // Tabs (Tab Bar)
        "tab.trips": "Trips",
        "tab.meals": "Meals",
        "tab.accommodation": "Accommodation",
        "tab.vehicle": "Vehicle",
        "tab.overview": "Overview",
        "tab.fahrten": "Trips",
        "tab.arbeitszeit": "Allowances",
        "tab.uebernachtung": "Overnight",
        "tab.kfz": "Vehicle",
        "tab.statistik": "Statistics",
        "tab.search": "Search",

        // TravelRegion
        "region.inland": "Domestic",
        "region.schweiz": "Switzerland",
        "region.ausland": "Abroad",

        // HotelMode
        "hotel.mode.flat": "Flat Rate",
        "hotel.mode.actual": "Actual Amount",

        // VehicleCostCategory
        "vehicle.cat.werkstatt": "Workshop / Repair",
        "vehicle.cat.versicherung": "Insurance",
        "vehicle.cat.tuev": "Inspection",
        "vehicle.cat.steuer": "Vehicle Tax",
        "vehicle.cat.reifen": "Tires",
        "vehicle.cat.leasing": "Leasing",
        "vehicle.cat.strom": "Electricity / Charging",
        "vehicle.cat.waesche": "Car Wash",
        "vehicle.cat.sonstiges": "Miscellaneous",

        // ReisespesenKategorie
        "kfz.cat.werkstatt": "Workshop",
        "kfz.cat.leasing": "Leasing",
        "kfz.cat.vignette": "Vignette / Toll",
        "kfz.cat.benzin": "Gasoline",
        "kfz.cat.strom": "Electricity / Charging",
        "kfz.cat.steuer": "Vehicle Tax",
        "kfz.cat.versicherung": "Vehicle Insurance",
        "kfz.cat.verpflegung": "Meals",
        "kfz.cat.sonstiges": "Miscellaneous",

        // KFZ view strings
        "kfz.title": "Vehicle Costs",
        "kfz.belege": "Receipts",
        "kfz.manual": "Add manually",
        "kfz.scan": "Scan receipt",
        "kfz.scan.hint": "Camera or photo – data is detected automatically",
        "kfz.empty.title": "Vehicle Costs",
        "kfz.empty.subtitle": "Track workshop, leasing, fuel and other costs",
        "kfz.empty.scan": "Scan",
        "kfz.empty.manual": "Manual",
        "kfz.kategorie": "Category",
        "kfz.betrag": "Amount",
        "kfz.notiz": "Note",
        "kfz.bezeichnung": "Description",
        "kfz.add.first": "Add first entry",
        "kfz.ausgaben": "Expenses",
        "kfz.netto": "Net",
        "kfz.waesche.title": "Car Wash",
        "kfz.waesche.hint": "Tap + to record a car wash.",
        "kfz.waesche.gesamt": "Total",
        "kfz.standard.kwh": "Ø Use default value (0.30 €/kWh)",

        // Overview
        "overview.empty.title": "No Data",
        "overview.empty.subtitle": "Record trips, meals, or\naccommodation",
        "overview.total": "Total Reimbursement",
        "overview.trips.unit": "Trips",
        "overview.days.unit": "Days",
        "overview.nights.unit": "Nights",
        "overview.accommodation.short": "Accomm.",

        // Trips
        "trips.gps.tile": "Start\nRecording",
        "trips.gps.menu": "GPS Recording",
        "trips.new.tile": "New\nTrip",
        "trips.empty.title": "No Trips",
        "trips.empty.subtitle": "Start GPS recording or add a trip manually",
        "trips.all": "All Trips",
        "trips.unit": "Trip(s)",
        "trips.form.new": "New Trip",
        "trips.form.edit": "Edit Trip",
        "trips.from": "From",
        "trips.to": "To",
        "trips.km.label": "Kilometers",
        "trips.result": "Result",
        "trips.distance": "Distance",
        "trips.rate": "Rate",
        "trips.reimbursement": "Reimbursement",
        "trips.start": "Start Location",
        "trips.destination": "Destination",
        "trips.route": "Route",
        "trips.navigation.section": "Navigation",
        "trips.calculation": "Calculation",
        "trips.maps.title": "Maps Integration",
        "trips.maps.subtitle": "Automatic route calculation · Pro only",
        "trips.maps.open": "Open navigation with",
        "trips.apple.maps": "Apple Maps",
        "trips.google.maps": "Google Maps",
        "trips.maps.open.btn": "Open in Maps",
        "trips.auto.label": "Automatic",
        "trips.auto.hint": "Enter start and destination – km will be calculated automatically",
        "trips.auto.calc": "Calculating automatically…",
        "trips.route.computing": "Route calculating automatically…",
        "trips.route.error": "Please check start and destination",
        "trips.live.route": "Live Route",
        "trips.gps.title": "GPS Trip",
        "trips.gps.heading": "Record GPS Trip",
        "trips.gps.desc": "The traveled distance is measured via GPS\nand automatically transferred.",
        "trips.gps.startbtn": "Start Recording",
        "trips.gps.running": "Recording in progress",
        "trips.gps.stop": "End Trip & Transfer",
        "trips.gps.permission": "Requesting location permission…",
        "trips.gps.permission.desc": "Please allow location access in the dialog.",
        "trips.gps.geocoding": "Determining addresses…",
        "trips.gps.geocoding.wait": "One moment please",
        "trips.gps.detected": "GPS Trip Detected",
        "trips.gps.detected.desc": "Distance, start and destination were determined automatically. Please check and correct if necessary.",
        "trips.gps.waiting": "Waiting for GPS…",
        "trips.nav.start": "Start Navigation",

        // Meals
        "meals.add": "Add Meal",
        "meals.add.hint": "Tap to add a day",
        "meals.all": "All Entries",
        "meals.unit": "Day(s)",
        "meals.form.new": "New Meal",
        "meals.form.edit": "Edit Entry",
        "meals.region": "Travel Region",
        "meals.absence": "Absence Time",
        "meals.begin": "Start",
        "meals.end": "End",
        "meals.result": "Result",
        "meals.absence.label": "Absence",
        "meals.level": "Level",
        "meals.allowance": "Meal Allowance",
        "meals.badge.none": "None",
        "meals.level.none": "None (< 1 h)",
        "meals.level.1": "Level 1 (1–3 h)",
        "meals.level.2": "Level 2 (3–6 h)",
        "meals.level.3": "Level 3 (6+ h)",

        // Accommodation
        "hotel.title": "Accommodation",
        "hotel.add": "Add Accommodation",
        "hotel.add.hint": "Tap to add accommodation",
        "hotel.all": "All Accommodations",
        "hotel.unit": "Night(s)",
        "hotel.section": "Accommodation",
        "hotel.form.new": "New Accommodation",
        "hotel.form.edit": "Edit Accommodation",
        "hotel.city": "City / Location",
        "hotel.city.placeholder": "e.g. London",
        "hotel.name": "Hotel",
        "hotel.billing": "Billing Method",
        "hotel.type": "Type",
        "hotel.cost": "Amount (€)",
        "hotel.reimbursement": "Reimbursement",
        "hotel.flat.label": "Accommodation Allowance",
        "hotel.actual.cost": "Actual Costs",
        "hotel.flat.badge": "Flat Rate",
        "hotel.actual.badge": "Actual Amount",
        "hotel.info": "Allowance %@ / night. If actual costs exceed the allowance, the full amount is reimbursed.",
        "hotel.over.flat": "Over Allowance (%@)",

        // Vehicle
        "vehicle.title": "Vehicle Costs",
        "vehicle.add": "Add Vehicle Costs",
        "vehicle.add.hint": "Workshop, insurance, or other vehicle costs",
        "vehicle.unit": "Entry/Entries",
        "vehicle.form.new": "New Costs",
        "vehicle.form.edit": "Edit Costs",
        "vehicle.category.section": "Category",
        "vehicle.details": "Details",
        "vehicle.title.label": "Description",
        "vehicle.mileage": "Mileage (km)",
        "vehicle.summary": "Summary",

        // Navigation titles
        "nav.arbeitszeit": "Allowances & Expenses",
        "nav.kfz": "Vehicle Costs",
        "nav.search": "Search",
        "nav.uebernachtung": "Accommodation",
        "nav.trips": "Trips",

        // Misc
        "misc.today": "Today",
        "misc.details": "Details",
        "misc.date": "Date",
        "misc.optional": "Optional",
        "misc.no.entries": "No Entries",
        "misc.no.entries.period": "No entries in selected period",
        "misc.trip.end": "End Trip",
        "misc.edit": "Edit",
        "misc.new": "New",
        "misc.all.trips": "All Trips",
        "misc.copy": "Copy",
        "misc.send": "Send",
        "misc.manage": "Manage",
        "misc.stop": "Stop",
        "misc.resume": "Resume now",
        "misc.end.trip": "End Trip",
        "misc.recorded.so.far": "recorded so far",
        "misc.paused": "Paused",
        "misc.loading": "Loading…",
        "misc.private": "Private",
        "misc.business": "Business",
        "misc.no.entries.search": "No entries found",
        "misc.search.hint": "Type a keyword or\nselect a date",
        "misc.search.hint2": "Try a different keyword\nor another date",

        // Filter chips
        "filter.day": "Day",
        "filter.week": "Week",
        "filter.month": "Month",
        "filter.all": "All",
        "filter.year": "Year",

        // Arbeitszeit
        "arbeitszeit.add.title": "Add Work Day",
        "arbeitszeit.add.subtitle": "Record total working time and meal allowance",
        "arbeitszeit.no.entries": "No entries in selected period",
        "arbeitszeit.monteur": "Mechanic's allowance (payroll, separate)",
        "arbeitszeit.wochenende": "Weekend/holiday allowance (payroll, separate)",

        // Settings
        "settings.title": "Settings",
        "settings.km.title": "Kilometer Reimbursement",
        "settings.km.rate": "Km Rate",
        "settings.km.footer": "Tax maximum 2026: 0.38 € / km for cars",
        "settings.meals.title": "Meal Allowances",
        "settings.meals.footer": "All amounts are freely configurable. Allowances under 1 h absence are always 0 €.",
        "settings.hotel.footer": "Germany standard: 20.00 € / night (§ 9 para. 1 no. 5a EStG). Cross-border workers with a Swiss employer working in Germany: please check individually. Custom amounts can be entered freely.",
        "settings.hours.1to3": "1 – 3 Hours",
        "settings.hours.3to6": "3 – 6 Hours",
        "settings.hours.6plus": "6+ Hours",
        "settings.reset": "Reset to Defaults",
        "settings.diagnosis": "Diagnosis",
        "settings.feedback": "Feedback & Support",
        "settings.log": "Error Log",
        "settings.info": "Info & Legal",
        "settings.privacy": "Privacy",
        "settings.help": "App Features & Help",
        "settings.imprint": "Imprint",
        "settings.language": "Language",
        "settings.language.section": "App Language",
        "settings.log.empty": "No entries.",
        "settings.log.clear": "Clear log?",
        "settings.gps.carplay": "Start GPS on CarPlay connection",
        "settings.gps.carplay.footer": "Automatically starts GPS recording when your iPhone connects to CarPlay.",
        "settings.home.address": "Home address",
        "settings.home.footer": "Shown as a quick-access button (🏠) in the trip form and highlighted in the trip list.",
        "settings.km.label": "Km allowance",
        "settings.km.legal.footer": "Statutory default: 0.38 € / km (§ 9 para. 1 no. 4a EStG, since January 2026)",
        "settings.chf.rate": "Rate (EUR = … CHF)",
        "settings.region.inland": "Domestic",
        "settings.region.schweiz": "Switzerland (in CHF)",
        "settings.region.ausland": "Abroad",
        "settings.meals.values.footer": "Domestic: 0 € · 14 € · 28 €  |  Switzerland: 0 · 65 · 65 CHF  |  Abroad: 0 € · 10 € · 35 €",
        "settings.mechanic.allowance": "Mechanic's Allowance",
        "settings.weekend.allowance": "Weekend / Holiday Allowance",
        "settings.hotel.title": "Accommodation / Breakfast",
        "settings.hotel.flat": "Accommodation flat rate",
        "settings.hotel.breakfast": "Breakfast flat rate",
        "settings.fuel.type": "Drive / Fuel type",
        "settings.fuel.label": "Drive / Fuel",
        "settings.fuel.consumption.kwh": "Consumption (kWh/100 km)",
        "settings.fuel.consumption": "Average consumption",
        "settings.fuel.price.electricity": "Default electricity price",
        "settings.fuel.price": "Default fuel price",
        "settings.privacy.label": "Privacy Policy",
        "settings.help.label": "App Features & Guide",
        "settings.mechanic.inland.label": "Allowance Domestic / Germany",
        "settings.mechanic.swiss.label": "Allowance Switzerland / Outside plant",
        "settings.mechanic.abroad.label": "Allowance Abroad / Outside plant & Germany",
        "settings.weekend.inland.label": "Allowance Domestic / Europe",
        "settings.weekend.swiss.label": "Allowance Switzerland / Europe",
        "settings.weekend.abroad.label": "Allowance Abroad / Other regions",
        "settings.mechanic.footer": "Flat allowance: €12 domestic, CHF 18 Switzerland, €50 abroad (or Switzerland if working at plant). Paid via payroll, NOT part of reimbursement.",
        "settings.weekend.footer": "Flat daily allowance domestic/Switzerland (€60 / CHF 90) or abroad (€72). Applies Sat/Sun or holidays. Paid via payroll, NOT part of reimbursement.",
        "settings.fuel.footer": "Drive type, price and consumption are auto-filled when adding new trips. Empty = manual input per trip.",
        "settings.reset.footer": "Restores all statutory defaults according to § 9 para. 4a EStG.",
        "settings.reset.confirm": "All flat rates will be reset to the statutory default values.",
        "settings.backup": "Backup & Restore",
        "settings.backup.save.local": "Save backup locally",
        "settings.backup.share": "Share backup / export to cloud",
        "settings.backup.restore": "Restore backup",
        "settings.backup.saved": "Saved backups",
        "settings.backup.footer": "'Save locally' stores the backup in the Files app. 'Share' enables export to iCloud Drive, Google Drive or via AirDrop. Max. 10 backups are kept.",
        "settings.delete.all": "Delete all entries",
        "settings.delete.footer": "Permanently deletes all entries. Settings are preserved.",
        "settings.manage.data": "Manage data",
        "settings.app.info": "App Info & Privacy",
        "settings.version": "App Version",
        "settings.developer": "Developer",
        "settings.contact": "Contact",
        "settings.log.section": "Log & Feedback",
        "settings.log.title": "App Log",
        "settings.log.empty.desc": "The log is empty.",
        "settings.log.show": "Show log",
        "settings.swipe.actions": "Sets which action and color appears when swiping left or right.",
        "settings.swipe.delete": "Delete",
        "settings.swipe.edit": "Edit",
        "settings.swipe.copy": "Copy",
        "settings.swipe.none": "-",
        "settings.swipe.title": "Swipe Gestures",
        "settings.swipe.left": "Swipe left",
        "settings.swipe.right1": "Swipe right 1",
        "settings.swipe.right2": "Swipe right 2",
        "settings.accessibility": "Accessibility",
        "settings.log.delete": "Clear log",
        "settings.log.delete.title": "Clear log?",
        "settings.log.delete.msg": "The log will be cleared. It will be automatically recreated on the next app start.",
        "settings.log.deleted": "Log cleared.",
        "settings.log.mem.note": "The log is stored in memory only and automatically cleared on the next app start. It contains no personal data.",
        "settings.language.footer": "The app uses the iOS system language. To change: Settings → General → Language & Region → iPhone Language.",
        "settings.delete.confirm": "This action cannot be undone. Create a backup first.",
        "settings.restore.confirm": "All current data will be replaced by the backup data.",
        "settings.delete.all.title": "Delete all entries?",
        "settings.delete.all.btn": "Delete all",
        "settings.all.deleted": "All entries have been deleted.",
        "settings.restore.title": "Restore backup?",
        "settings.restore.btn": "Load backup",
        "settings.reset.title": "Restore defaults?",
        "settings.reset.btn": "Reset",
        "settings.backup.loading": "Loading backups…",
        "settings.backup.empty.title": "No iCloud backups yet",
        "settings.backup.empty.hint": "Create a backup via Settings → iCloud Backup",
        "settings.backup.saved.title": "Saved backups",
        "settings.backup.restore.btn": "Restore",
        "settings.backup.restore.msg": "All current data will be replaced by the backup from %@.",
        "settings.backup.delete.title": "Delete backup?",
        "settings.scan.receipt": "Scan receipt",
        "settings.scan.receipt.hint": "Automatically detect items, categories and amounts",
        "settings.entry.add": "Add entry",

        // Overview
        "overview.ausgaben": "Expenses",
        "overview.not.reimbursable": "not reimbursable",
        "overview.total.ausgaben": "Total Expenses",
        "overview.meal.balance": "Meal Balance",
        "overview.flat.label": "Allowance",
        "overview.fuel": "Fuel / Electricity",
        "overview.driven.km": "Driven km costs",
        "overview.meal.expenses": "Meal Expenses",
        "overview.travel.expenses": "Travel Expenses / Vehicle",
        "overview.private.expenses": "Private Expenses",
        "overview.entry": "Entry",
        "overview.entries": "Entries",
        "overview.no.entries": "No entries",

        // Filter
        "filter.woche": "Week",
        "filter.monat": "Month",
        "filter.jahr": "Year",

        // Statistik
        "stat.tab.months": "Months",
        "stat.tab.routes": "Routes",
        "stat.tab.tax": "Tax",
        "stat.reimbursement.per.month": "Reimbursement per Month",
        "stat.best.month": "Best month: **%@** with %@",
        "stat.top.routes": "Top Routes",
        "stat.tax.year": "Tax Year %@",
        "stat.total.reimbursement": "Total Reimbursement %@",
        "stat.tax.annex.n": "For Annex N / Business Travel Report",
        "stat.mechanic.allowance": "Mechanic's Allowance %@",
        "stat.payroll.note": "Payroll component – not part of travel expenses (Annex N)",
        "stat.disclaimer": "This report is for guidance only. Please verify the amounts with your tax advisor or tax software.",

        // Summary tiles
        "stat.trips.label": "Trips",
        "stat.km.label": "Kilometers",
        "stat.reimbursement.label": "Reimbursement",
    ],

    .polish: [
        // Actions
        "action.add": "Dodaj",
        "action.edit": "Edytuj",
        "action.delete": "Usuń",
        "action.cancel": "Anuluj",
        "action.save": "Zapisz",
        "action.done": "Gotowe",
        "action.close": "Zamknij",

        // Common
        "common.optional": "Opcjonalnie",
        "common.note": "Notatka",
        "common.date": "Data",
        "common.amount": "Kwota",
        "common.region": "Region",

        // Tabs (Tab Bar)
        "tab.trips": "Podróże",
        "tab.meals": "Posiłki",
        "tab.accommodation": "Noclegi",
        "tab.vehicle": "Pojazd",
        "tab.overview": "Przegląd",
        "tab.fahrten": "Podróże",
        "tab.arbeitszeit": "Diety",
        "tab.uebernachtung": "Noclegi",
        "tab.kfz": "Pojazd",
        "tab.statistik": "Statystyki",
        "tab.search": "Szukaj",

        // TravelRegion
        "region.inland": "Kraj",
        "region.schweiz": "Szwajcaria",
        "region.ausland": "Zagranica",

        // HotelMode
        "hotel.mode.flat": "Ryczałt",
        "hotel.mode.actual": "Rzeczywista kwota",

        // VehicleCostCategory
        "vehicle.cat.werkstatt": "Warsztat / Naprawa",
        "vehicle.cat.versicherung": "Ubezpieczenie",
        "vehicle.cat.tuev": "Przegląd",
        "vehicle.cat.steuer": "Podatek od pojazdu",
        "vehicle.cat.reifen": "Opony",
        "vehicle.cat.leasing": "Leasing",
        "vehicle.cat.strom": "Prąd / Ładowanie",
        "vehicle.cat.waesche": "Myjnia",
        "vehicle.cat.sonstiges": "Inne",

        // ReisespesenKategorie
        "kfz.cat.werkstatt": "Warsztat",
        "kfz.cat.leasing": "Leasing",
        "kfz.cat.vignette": "Winiety / Opłaty drogowe",
        "kfz.cat.benzin": "Benzyna",
        "kfz.cat.strom": "Prąd / Ładowanie",
        "kfz.cat.steuer": "Podatek drogowy",
        "kfz.cat.versicherung": "Ubezpieczenie pojazdu",
        "kfz.cat.verpflegung": "Wyżywienie",
        "kfz.cat.sonstiges": "Inne",

        // KFZ view strings
        "kfz.title": "Koszty pojazdu",
        "kfz.belege": "Paragonów",
        "kfz.manual": "Dodaj ręcznie",
        "kfz.scan": "Skanuj paragon",
        "kfz.scan.hint": "Aparat lub zdjęcie – dane są rozpoznawane automatycznie",
        "kfz.empty.title": "Koszty pojazdu",
        "kfz.empty.subtitle": "Rejestruj koszty warsztatu, leasingu, paliwa i inne",
        "kfz.empty.scan": "Skanuj",
        "kfz.empty.manual": "Ręcznie",
        "kfz.kategorie": "Kategoria",
        "kfz.betrag": "Kwota",
        "kfz.notiz": "Notatka",
        "kfz.bezeichnung": "Opis",
        "kfz.add.first": "Dodaj pierwszy wpis",
        "kfz.ausgaben": "Wydatki",
        "kfz.netto": "Netto",
        "kfz.waesche.title": "Mycie samochodu",
        "kfz.waesche.hint": "Kliknij + aby dodać mycie samochodu.",
        "kfz.waesche.gesamt": "Razem",
        "kfz.standard.kwh": "Ø Użyj wartości domyślnej (0,30 €/kWh)",

        // Overview
        "overview.empty.title": "Brak danych",
        "overview.empty.subtitle": "Zarejestruj podróże, posiłki lub\nnoclegi",
        "overview.total": "Całkowita zwrot",
        "overview.trips.unit": "Podróże",
        "overview.days.unit": "Dni",
        "overview.nights.unit": "Noce",
        "overview.accommodation.short": "Noclegi",

        // Trips
        "trips.gps.tile": "Rozpocznij\nnagrywanie",
        "trips.gps.menu": "Nagrywanie GPS",
        "trips.new.tile": "Nowa\npodróż",
        "trips.empty.title": "Brak podróży",
        "trips.empty.subtitle": "Rozpocznij nagrywanie GPS lub dodaj podróż ręcznie",
        "trips.all": "Wszystkie podróże",
        "trips.unit": "Podróż/e",
        "trips.form.new": "Nowa podróż",
        "trips.form.edit": "Edytuj podróż",
        "trips.from": "Z",
        "trips.to": "Do",
        "trips.km.label": "Kilometry",
        "trips.result": "Wynik",
        "trips.distance": "Odległość",
        "trips.rate": "Stawka",
        "trips.reimbursement": "Zwrot",
        "trips.start": "Lokalizacja początkowa",
        "trips.destination": "Cel podróży",
        "trips.route": "Trasa",
        "trips.navigation.section": "Nawigacja",
        "trips.calculation": "Obliczanie",
        "trips.maps.title": "Integracja map",
        "trips.maps.subtitle": "Automatyczne obliczanie trasy · tylko w wersji Pro",
        "trips.maps.open": "Otwórz nawigację za pomocą",
        "trips.apple.maps": "Apple Maps",
        "trips.google.maps": "Google Maps",
        "trips.maps.open.btn": "Otwórz w Mapach",
        "trips.auto.label": "Automatycznie",
        "trips.auto.hint": "Wprowadź start i cel – km będą obliczane automatycznie",
        "trips.auto.calc": "Obliczanie automatyczne…",
        "trips.route.computing": "Trasa obliczana automatycznie…",
        "trips.route.error": "Proszę sprawdzić punkt startu i cel",
        "trips.live.route": "Trasa na żywo",
        "trips.gps.title": "Podróż GPS",
        "trips.gps.heading": "Nagraj podróż GPS",
        "trips.gps.desc": "Przebyta odległość jest mierzona za pośrednictwem GPS\ni automatycznie przesyłana.",
        "trips.gps.startbtn": "Rozpocznij nagrywanie",
        "trips.gps.running": "Nagrywanie w toku",
        "trips.gps.stop": "Zakończ podróż i prześlij",
        "trips.gps.permission": "Żądanie uprawnień do lokalizacji…",
        "trips.gps.permission.desc": "Proszę zezwolić na dostęp do lokalizacji w oknie dialogowym.",
        "trips.gps.geocoding": "Określanie adresów…",
        "trips.gps.geocoding.wait": "Moment proszę",
        "trips.gps.detected": "Wykryta podróż GPS",
        "trips.gps.detected.desc": "Odległość, punkt początkowy i cel zostały określone automatycznie. Proszę sprawdzić i w razie potrzeby poprawić.",
        "trips.gps.waiting": "Czekaj na GPS…",
        "trips.nav.start": "Uruchom nawigację",

        // Meals
        "meals.add": "Dodaj posiłek",
        "meals.add.hint": "Dotknij, aby dodać dzień",
        "meals.all": "Wszystkie wpisy",
        "meals.unit": "Dzień/dni",
        "meals.form.new": "Nowy posiłek",
        "meals.form.edit": "Edytuj wpis",
        "meals.region": "Region podróży",
        "meals.absence": "Czas nieobecności",
        "meals.begin": "Początek",
        "meals.end": "Koniec",
        "meals.result": "Wynik",
        "meals.absence.label": "Nieobecność",
        "meals.level": "Poziom",
        "meals.allowance": "Zasiłek na posiłki",
        "meals.badge.none": "Brak",
        "meals.level.none": "Brak (< 1 h)",
        "meals.level.1": "Poziom 1 (1–3 h)",
        "meals.level.2": "Poziom 2 (3–6 h)",
        "meals.level.3": "Poziom 3 (6+ h)",

        // Accommodation
        "hotel.title": "Noclegi",
        "hotel.add": "Dodaj nocleg",
        "hotel.add.hint": "Dotknij, aby dodać nocleg",
        "hotel.all": "Wszystkie noclegi",
        "hotel.unit": "Noc/noce",
        "hotel.section": "Nocleg",
        "hotel.form.new": "Nowy nocleg",
        "hotel.form.edit": "Edytuj nocleg",
        "hotel.city": "Miasto / Lokalizacja",
        "hotel.city.placeholder": "np. Warszawa",
        "hotel.name": "Hotel",
        "hotel.billing": "Metoda rozliczenia",
        "hotel.type": "Typ",
        "hotel.cost": "Kwota (€)",
        "hotel.reimbursement": "Zwrot",
        "hotel.flat.label": "Zasiłek noclegowy",
        "hotel.actual.cost": "Koszty rzeczywiste",
        "hotel.flat.badge": "Ryczałt",
        "hotel.actual.badge": "Rzeczywista kwota",
        "hotel.info": "Zasiłek %@ / noc. Jeśli koszty rzeczywiste przekraczają zasiłek, pełna kwota jest zwracana.",
        "hotel.over.flat": "Nad zasiłkiem (%@)",

        // Vehicle
        "vehicle.title": "Koszty pojazdu",
        "vehicle.add": "Dodaj koszty pojazdu",
        "vehicle.add.hint": "Warsztat, ubezpieczenie lub inne koszty pojazdu",
        "vehicle.unit": "Wpis/Wpisy",
        "vehicle.form.new": "Nowe koszty",
        "vehicle.form.edit": "Edytuj koszty",
        "vehicle.category.section": "Kategoria",
        "vehicle.details": "Szczegóły",
        "vehicle.title.label": "Opis",
        "vehicle.mileage": "Przebieg (km)",
        "vehicle.summary": "Podsumowanie",

        // Navigation titles
        "nav.arbeitszeit": "Diety i wydatki",
        "nav.kfz": "Koszty pojazdu",
        "nav.search": "Szukaj",
        "nav.uebernachtung": "Noclegi",
        "nav.trips": "Podróże",

        // Misc
        "misc.today": "Dzisiaj",
        "misc.details": "Szczegóły",
        "misc.date": "Data",
        "misc.optional": "Opcjonalnie",
        "misc.no.entries": "Brak wpisów",
        "misc.no.entries.period": "Brak wpisów w wybranym okresie",
        "misc.trip.end": "Zakończ podróż",
        "misc.edit": "Edytuj",
        "misc.new": "Nowy",
        "misc.all.trips": "Wszystkie podróże",
        "misc.copy": "Kopiuj",
        "misc.send": "Wyślij",
        "misc.manage": "Zarządzaj",
        "misc.stop": "Zatrzymaj",
        "misc.resume": "Wznów teraz",
        "misc.end.trip": "Zakończ podróż",
        "misc.recorded.so.far": "zarejestrowane",
        "misc.paused": "Wstrzymano",
        "misc.loading": "Ładowanie…",
        "misc.private": "Prywatny",
        "misc.business": "Służbowy",
        "misc.no.entries.search": "Nie znaleziono wpisów",
        "misc.search.hint": "Wpisz słowo lub\nwybierz datę",
        "misc.search.hint2": "Spróbuj innego słowa\nlub innej daty",
        "filter.day": "Dzień",
        "filter.week": "Tydzień",
        "filter.month": "Miesiąc",
        "filter.all": "Wszystkie",
        "filter.year": "Rok",
        "arbeitszeit.add.title": "Dodaj dzień pracy",
        "arbeitszeit.add.subtitle": "Zarejestruj czas pracy i dietę",
        "arbeitszeit.no.entries": "Brak wpisów w wybranym okresie",
        "arbeitszeit.monteur": "Dodatek montera (płaca, osobno)",
        "arbeitszeit.wochenende": "Dodatek weekendowy/świąteczny (płaca, osobno)",

        // Settings
        "settings.title": "Ustawienia",
        "settings.km.title": "Zwrot za kilometry",
        "settings.km.rate": "Stawka za km",
        "settings.km.footer": "Maksimum podatkowe 2026: 0,38 € / km dla samochodów",
        "settings.meals.title": "Zasiłki na posiłki",
        "settings.meals.footer": "Wszystkie kwoty można swobodnie konfigurować. Zasiłki poniżej 1 h nieobecności zawsze wynoszą 0 €.",
        "settings.hotel.footer": "Standard Niemcy: 20,00 € / noc (§ 9 ust. 1 nr 5a EStG). Pracownicy transgraniczni ze szwajcarskim pracodawcą pracujący w Niemczech: prosimy sprawdzić indywidualnie. Kwoty niestandardowe można wprowadzać swobodnie.",
        "settings.hours.1to3": "1 – 3 godziny",
        "settings.hours.3to6": "3 – 6 godzin",
        "settings.hours.6plus": "6+ godzin",
        "settings.reset": "Przywróć ustawienia domyślne",
        "settings.diagnosis": "Diagnostyka",
        "settings.feedback": "Opinia i wsparcie",
        "settings.log": "Dziennik błędów",
        "settings.info": "Informacje i prawo",
        "settings.privacy": "Prywatność",
        "settings.help": "Funkcje aplikacji i pomoc",
        "settings.imprint": "Zastrzeżenia",
        "settings.language": "Język",
        "settings.language.section": "Język aplikacji",
        "settings.log.empty": "Brak wpisów.",
        "settings.log.clear": "Wyczyścić dziennik?",
        "settings.gps.carplay": "Uruchom GPS po połączeniu z CarPlay",
        "settings.gps.carplay.footer": "Automatycznie uruchamia zapis GPS po podłączeniu iPhone do CarPlay.",
        "settings.home.address": "Adres domowy",
        "settings.home.footer": "Wyświetlany jako przycisk (🏠) w formularzu podróży i zaznaczony na liście podróży.",
        "settings.km.label": "Stawka za km",
        "settings.km.legal.footer": "Maksimum podatkowe 2026: 0,38 € / km",
        "settings.chf.rate": "Kurs (EUR = … CHF)",
        "settings.region.inland": "Kraj",
        "settings.region.schweiz": "Szwajcaria (w CHF)",
        "settings.region.ausland": "Zagranica",
        "settings.meals.values.footer": "Kraj: 0 € · 14 € · 28 €  |  Szwajcaria: 0 · 65 · 65 CHF  |  Zagranica: 0 € · 10 € · 35 €",
        "settings.mechanic.allowance": "Dodatek montera",
        "settings.weekend.allowance": "Dodatek weekendowy/świąteczny",
        "settings.hotel.title": "Nocleg/Śniadanie",
        "settings.hotel.flat": "Ryczałt za nocleg",
        "settings.hotel.breakfast": "Ryczałt za śniadanie",
        "settings.fuel.type": "Napęd / Rodzaj paliwa",
        "settings.fuel.label": "Napęd / Paliwo",
        "settings.fuel.consumption.kwh": "Zużycie (kWh/100 km)",
        "settings.fuel.consumption": "Średnie zużycie",
        "settings.fuel.price.electricity": "Domyślna cena prądu",
        "settings.fuel.price": "Domyślna cena paliwa",
        "settings.privacy.label": "Polityka prywatności",
        "settings.help.label": "Funkcje aplikacji & Przewodnik",
        "settings.mechanic.inland.label": "Zulage krajowy / Niemcy",
        "settings.mechanic.swiss.label": "Zulage Szwajcaria / Poza zakładem",
        "settings.mechanic.abroad.label": "Zulage zagranica / Poza zakładem i Niemcami",
        "settings.weekend.inland.label": "Zulage krajowy / Europa",
        "settings.weekend.swiss.label": "Zulage Szwajcaria / Europa",
        "settings.weekend.abroad.label": "Zulage zagranica / Inne regiony",
        "settings.mechanic.footer": "Ryczałt: 12 € krajowy, 18 CHF Szwajcaria, 50 € zagranica. Wypłacane przez wynagrodzenie, NIE wlicza się do zwrotu.",
        "settings.weekend.footer": "Dzienny ryczałt krajowy/Szwajcaria (60 € / 90 CHF) lub zagranica (72 €). Sobota/niedziela lub święta. NIE wlicza się do zwrotu.",
        "settings.fuel.footer": "Rodzaj napędu, cena i zużycie są automatycznie uzupełniane przy dodawaniu nowych podróży.",
        "settings.reset.footer": "Przywraca wszystkie ustawienia domyślne zgodnie z § 9 EStG.",
        "settings.reset.confirm": "Wszystkie ryczałty zostaną zresetowane do wartości ustawowych.",
        "settings.backup": "Backup i przywracanie",
        "settings.backup.save.local": "Zapisz backup lokalnie",
        "settings.backup.share": "Udostępnij backup / eksportuj do chmury",
        "settings.backup.restore": "Przywróć backup",
        "settings.backup.saved": "Zapisane kopie zapasowe",
        "settings.backup.footer": "Maks. 10 kopii zapasowych jest przechowywanych.",
        "settings.delete.all": "Usuń wszystkie wpisy",
        "settings.delete.footer": "Nieodwracalnie usuwa wszystkie wpisy. Ustawienia pozostają.",
        "settings.manage.data": "Zarządzaj danymi",
        "settings.app.info": "Informacje i prywatność",
        "settings.version": "Wersja aplikacji",
        "settings.developer": "Deweloper",
        "settings.contact": "Kontakt",
        "settings.log.section": "Dziennik i feedback",
        "settings.log.title": "Dziennik aplikacji",
        "settings.log.empty.desc": "Dziennik jest pusty.",
        "settings.log.show": "Pokaż dziennik",
        "settings.swipe.actions": "Określa akcję i kolor przy przesunięciu w lewo lub prawo.",
        "settings.swipe.delete": "Usuń",
        "settings.swipe.edit": "Edytuj",
        "settings.swipe.copy": "Kopiuj",
        "settings.swipe.none": "-",
        "settings.swipe.title": "Gesty przesunięcia",
        "settings.swipe.left": "Przesuń w lewo",
        "settings.swipe.right1": "Przesuń w prawo 1",
        "settings.swipe.right2": "Przesuń w prawo 2",
        "settings.accessibility": "Ułatwienia dostępu",
        "settings.log.delete": "Wyczyść dziennik",
        "settings.log.delete.title": "Wyczyścić dziennik?",
        "settings.log.delete.msg": "Dziennik zostanie wyczyszczony. Zostanie automatycznie odtworzony przy następnym uruchomieniu.",
        "settings.log.deleted": "Dziennik wyczyszczony.",
        "settings.log.mem.note": "Dziennik jest przechowywany tylko w pamięci i automatycznie czyszczony przy następnym uruchomieniu. Nie zawiera danych osobowych.",
        "settings.language.footer": "Aplikacja używa języka systemu iOS. Aby zmienić: Ustawienia → Ogólne → Język i region.",
        "settings.delete.confirm": "Tej operacji nie można cofnąć. Najpierw wykonaj kopię zapasową.",
        "settings.restore.confirm": "Wszystkie aktualne dane zostaną zastąpione danymi z kopii zapasowej.",
        "settings.delete.all.title": "Usunąć wszystkie wpisy?",
        "settings.delete.all.btn": "Usuń wszystko",
        "settings.all.deleted": "Wszystkie wpisy zostały usunięte.",
        "settings.restore.title": "Przywrócić kopię zapasową?",
        "settings.restore.btn": "Załaduj kopię",
        "settings.reset.title": "Przywrócić wartości domyślne?",
        "settings.reset.btn": "Zresetuj",
        "settings.backup.loading": "Ładowanie kopii…",
        "settings.backup.empty.title": "Brak kopii zapasowych iCloud",
        "settings.backup.empty.hint": "Utwórz kopię zapasową w Ustawienia → iCloud Backup",
        "settings.backup.saved.title": "Zapisane kopie zapasowe",
        "settings.backup.restore.btn": "Przywróć",
        "settings.backup.restore.msg": "Wszystkie dane zostaną zastąpione kopią z %@.",
        "settings.backup.delete.title": "Usunąć kopię zapasową?",
        "settings.scan.receipt": "Skanuj paragon",
        "settings.scan.receipt.hint": "Automatyczne wykrywanie pozycji, kategorii i kwot",
        "settings.entry.add": "Dodaj wpis",

        // Overview
        "overview.ausgaben": "Wydatki",
        "overview.not.reimbursable": "nierefundowane",
        "overview.total.ausgaben": "Łączne wydatki",
        "overview.meal.balance": "Saldo diety",
        "overview.flat.label": "Ryczałt",
        "overview.fuel": "Paliwo / Prąd",
        "overview.driven.km": "Koszty przejechanych km",
        "overview.meal.expenses": "Wydatki na wyżywienie",
        "overview.travel.expenses": "Reisespesen / KFZ",
        "overview.private.expenses": "Wydatki prywatne",
        "overview.entry": "Wpis",
        "overview.entries": "Wpisy",
        "overview.no.entries": "Brak wpisów",

        // Filter
        "filter.woche": "Tydzień",
        "filter.monat": "Miesiąc",
        "filter.jahr": "Rok",

        // Statistik
        "stat.tab.months": "Miesiące",
        "stat.tab.routes": "Trasy",
        "stat.tab.tax": "Podatek",
        "stat.reimbursement.per.month": "Zwrot na miesiąc",
        "stat.best.month": "Najlepszy miesiąc: **%@** z %@",
        "stat.top.routes": "Najpopularniejsze trasy",
        "stat.tax.year": "Rok podatkowy %@",
        "stat.total.reimbursement": "Łączny zwrot %@",
        "stat.tax.annex.n": "Dla Anlage N / rozliczenie kosztów podróży",
        "stat.mechanic.allowance": "Dodatek montera %@",
        "stat.payroll.note": "Składnik wynagrodzenia – nie część kosztów podróży (Anlage N)",
        "stat.disclaimer": "Zestawienie ma charakter orientacyjny. Sprawdź kwoty z doradcą podatkowym.",

        // Summary tiles
        "stat.trips.label": "Podróże",
        "stat.km.label": "Kilometry",
        "stat.reimbursement.label": "Zwrot",
    ],

    .czech: [
        // Actions
        "action.add": "Přidat",
        "action.edit": "Upravit",
        "action.delete": "Smazat",
        "action.cancel": "Zrušit",
        "action.save": "Uložit",
        "action.done": "Hotovo",
        "action.close": "Zavřít",

        // Common
        "common.optional": "Volitelné",
        "common.note": "Poznámka",
        "common.date": "Datum",
        "common.amount": "Částka",
        "common.region": "Oblast",

        // Tabs (Tab Bar)
        "tab.trips": "Jízdy",
        "tab.meals": "Stravné",
        "tab.accommodation": "Ubytování",
        "tab.vehicle": "Vozidlo",
        "tab.overview": "Přehled",
        "tab.fahrten": "Jízdy",
        "tab.arbeitszeit": "Stravné",
        "tab.uebernachtung": "Ubytov.",
        "tab.kfz": "Vozidlo",
        "tab.statistik": "Statistika",
        "tab.search": "Hledat",

        // TravelRegion
        "region.inland": "Tuzemsko",
        "region.schweiz": "Švýcarsko",
        "region.ausland": "Zahraničí",

        // HotelMode
        "hotel.mode.flat": "Paušál",
        "hotel.mode.actual": "Skutečná částka",

        // VehicleCostCategory
        "vehicle.cat.werkstatt": "Dílna / Oprava",
        "vehicle.cat.versicherung": "Pojištění",
        "vehicle.cat.tuev": "STK",
        "vehicle.cat.steuer": "Silniční daň",
        "vehicle.cat.reifen": "Pneumatiky",
        "vehicle.cat.leasing": "Leasing",
        "vehicle.cat.strom": "Elektřina / Nabíjení",
        "vehicle.cat.waesche": "Mytí vozidla",
        "vehicle.cat.sonstiges": "Ostatní",

        // ReisespesenKategorie
        "kfz.cat.werkstatt": "Servis",
        "kfz.cat.leasing": "Leasing",
        "kfz.cat.vignette": "Dálniční známka / Mýto",
        "kfz.cat.benzin": "Benzín",
        "kfz.cat.strom": "Elektřina / Nabíjení",
        "kfz.cat.steuer": "Daň z vozidla",
        "kfz.cat.versicherung": "Pojištění vozidla",
        "kfz.cat.verpflegung": "Stravné",
        "kfz.cat.sonstiges": "Ostatní",

        // KFZ view strings
        "kfz.title": "Náklady na vozidlo",
        "kfz.belege": "Dokladů",
        "kfz.manual": "Přidat ručně",
        "kfz.scan": "Naskenovat doklad",
        "kfz.scan.hint": "Fotoaparát nebo foto – data jsou rozpoznána automaticky",
        "kfz.empty.title": "Náklady na vozidlo",
        "kfz.empty.subtitle": "Evidujte náklady na servis, leasing, palivo a další",
        "kfz.empty.scan": "Skenovat",
        "kfz.empty.manual": "Ručně",
        "kfz.kategorie": "Kategorie",
        "kfz.betrag": "Částka",
        "kfz.notiz": "Poznámka",
        "kfz.bezeichnung": "Označení",
        "kfz.add.first": "Přidat první záznam",
        "kfz.ausgaben": "Výdaje",
        "kfz.netto": "Netto",
        "kfz.waesche.title": "Mytí vozidla",
        "kfz.waesche.hint": "Klepněte na + pro přidání mytí vozidla.",
        "kfz.waesche.gesamt": "Celkem",
        "kfz.standard.kwh": "Ø Použít výchozí hodnotu (0,30 €/kWh)",

        // Overview
        "overview.empty.title": "Žádná data",
        "overview.empty.subtitle": "Zaznamenejte jízdy, stravné nebo ubytování",
        "overview.total": "Celková náhrada",
        "overview.trips.unit": "Jízdy",
        "overview.days.unit": "Dny",
        "overview.nights.unit": "Noci",
        "overview.accommodation.short": "Ubytov.",

        // Trips
        "trips.gps.tile": "Spustit\nzáznam",
        "trips.gps.menu": "GPS záznam",
        "trips.new.tile": "Nová\njízda",
        "trips.empty.title": "Žádné jízdy",
        "trips.empty.subtitle": "Spusťte GPS záznam nebo přidejte jízdu ručně",
        "trips.all": "Všechny jízdy",
        "trips.unit": "jízda/jízdy",
        "trips.form.new": "Nová jízda",
        "trips.form.edit": "Upravit jízdu",
        "trips.from": "Odkud",
        "trips.to": "Kam",
        "trips.km.label": "Kilometry",
        "trips.result": "Výsledek",
        "trips.distance": "Vzdálenost",
        "trips.rate": "Sazba",
        "trips.reimbursement": "Náhrada",
        "trips.start": "Místo odjezdu",
        "trips.destination": "Cíl",
        "trips.route": "Trasa",
        "trips.navigation.section": "Navigace",
        "trips.calculation": "Výpočet",
        "trips.maps.title": "Integrace Map",
        "trips.maps.subtitle": "Automatický výpočet trasy · pouze Pro",
        "trips.maps.open": "Otevřít navigaci v",
        "trips.apple.maps": "Apple Maps",
        "trips.google.maps": "Google Maps",
        "trips.maps.open.btn": "Otevřít v Mapách",
        "trips.auto.label": "Automaticky",
        "trips.auto.hint": "Zadejte start a cíl – km se vypočítají automaticky",
        "trips.auto.calc": "Počítám automaticky…",
        "trips.route.computing": "Trasa se počítá automaticky…",
        "trips.route.error": "Zkontrolujte start a cíl",
        "trips.live.route": "Živá trasa",
        "trips.gps.title": "GPS jízda",
        "trips.gps.heading": "Zaznamenat GPS jízdu",
        "trips.gps.desc": "Ujetá vzdálenost je měřena GPS\na automaticky přenesena.",
        "trips.gps.startbtn": "Spustit záznam",
        "trips.gps.running": "Záznam probíhá",
        "trips.gps.stop": "Ukončit jízdu & přenést",
        "trips.gps.permission": "Vyžaduji povolení polohy…",
        "trips.gps.permission.desc": "Povolte přístup k poloze v dialogu.",
        "trips.gps.geocoding": "Zjišťuji adresy…",
        "trips.gps.geocoding.wait": "Moment prosím",
        "trips.gps.detected": "Detekována GPS jízda",
        "trips.gps.detected.desc": "Vzdálenost, start a cíl byly určeny automaticky. Zkontrolujte a případně opravte.",
        "trips.gps.waiting": "Čekám na GPS…",
        "trips.nav.start": "Spustit navigaci",

        // Meals
        "meals.add": "Přidat stravné",
        "meals.add.hint": "Klepněte pro přidání dne",
        "meals.all": "Všechny záznamy",
        "meals.unit": "Den/dny",
        "meals.form.new": "Nové stravné",
        "meals.form.edit": "Upravit záznam",
        "meals.region": "Oblast cestování",
        "meals.absence": "Doba nepřítomnosti",
        "meals.begin": "Začátek",
        "meals.end": "Konec",
        "meals.result": "Výsledek",
        "meals.absence.label": "Nepřítomnost",
        "meals.level": "Stupeň",
        "meals.allowance": "Stravné",
        "meals.badge.none": "Žádné",
        "meals.level.none": "Žádné (< 1 h)",
        "meals.level.1": "Stupeň 1 (1–3 h)",
        "meals.level.2": "Stupeň 2 (3–6 h)",
        "meals.level.3": "Stupeň 3 (6+ h)",

        // Accommodation
        "hotel.title": "Ubytování",
        "hotel.add": "Přidat ubytování",
        "hotel.add.hint": "Klepněte pro přidání ubytování",
        "hotel.all": "Všechna ubytování",
        "hotel.unit": "noc/nocí",
        "hotel.section": "Ubytování",
        "hotel.form.new": "Nové ubytování",
        "hotel.form.edit": "Upravit ubytování",
        "hotel.city": "Město / místo",
        "hotel.city.placeholder": "např. Praha",
        "hotel.name": "Hotel",
        "hotel.billing": "Způsob účtování",
        "hotel.type": "Typ",
        "hotel.cost": "Částka (€)",
        "hotel.reimbursement": "Náhrada",
        "hotel.flat.label": "Paušální náhrada za ubytování",
        "hotel.actual.cost": "Skutečné náklady",
        "hotel.flat.badge": "Paušál",
        "hotel.actual.badge": "Skutečná částka",
        "hotel.info": "Paušál %@ / noc. Pokud skutečné náklady překračují paušál, uhradí se plná částka.",
        "hotel.over.flat": "Nad paušálem (%@)",

        // Vehicle
        "vehicle.title": "Náklady na vozidlo",
        "vehicle.add": "Přidat náklady na vozidlo",
        "vehicle.add.hint": "Dílna, pojištění nebo jiné náklady na vozidlo",
        "vehicle.unit": "Záznam/záznamy",
        "vehicle.form.new": "Nové náklady",
        "vehicle.form.edit": "Upravit náklady",
        "vehicle.category.section": "Kategorie",
        "vehicle.details": "Detaily",
        "vehicle.title.label": "Popis",
        "vehicle.mileage": "Stav km",
        "vehicle.summary": "Souhrn",

        // Navigation titles
        "nav.arbeitszeit": "Stravné a výdaje",
        "nav.kfz": "Náklady na vozidlo",
        "nav.search": "Hledat",
        "nav.uebernachtung": "Ubytování",
        "nav.trips": "Jízdy",

        // Misc
        "misc.today": "Dnes",
        "misc.details": "Podrobnosti",
        "misc.date": "Datum",
        "misc.optional": "Volitelné",
        "misc.no.entries": "Žádné záznamy",
        "misc.no.entries.period": "Žádné záznamy ve zvoleném období",
        "misc.trip.end": "Ukončit jízdu",
        "misc.edit": "Upravit",
        "misc.new": "Nový",
        "misc.all.trips": "Všechny jízdy",
        "misc.copy": "Kopírovat",
        "misc.send": "Odeslat",
        "misc.manage": "Spravovat",
        "misc.stop": "Zastavit",
        "misc.resume": "Pokračovat nyní",
        "misc.end.trip": "Ukončit jízdu",
        "misc.recorded.so.far": "zaznamenáno",
        "misc.paused": "Pozastaveno",
        "misc.loading": "Načítání…",
        "misc.private": "Soukromé",
        "misc.business": "Pracovní",
        "misc.no.entries.search": "Žádné záznamy nalezeny",
        "misc.search.hint": "Zadejte výraz nebo\nvyberte datum",
        "misc.search.hint2": "Zkuste jiný výraz\nnebo jiné datum",
        "filter.day": "Den",
        "filter.week": "Týden",
        "filter.month": "Měsíc",
        "filter.all": "Vše",
        "filter.year": "Rok",
        "arbeitszeit.add.title": "Přidat pracovní den",
        "arbeitszeit.add.subtitle": "Zaznamenat pracovní dobu a stravné",
        "arbeitszeit.no.entries": "Žádné záznamy ve zvoleném období",
        "arbeitszeit.monteur": "Příplatek montéra (mzda, zvlášť)",
        "arbeitszeit.wochenende": "Příplatek za víkend/svátky (mzda, zvlášť)",

        // Settings
        "settings.title": "Nastavení",
        "settings.km.title": "Náhrada za km",
        "settings.km.rate": "Sazba za km",
        "settings.km.footer": "Daňové maximum 2026: 0,38 € / km pro osobní automobily",
        "settings.meals.title": "Stravné",
        "settings.meals.footer": "Všechny částky jsou volně konfigurovatelné. Stravné při nepřítomnosti do 1 h je vždy 0 €.",
        "settings.hotel.footer": "Standard Německo: 20,00 € / noc (§ 9 odst. 1 č. 5a EStG). Přeshraniční pracovníci se švýcarským zaměstnavatelem pracující v Německu: prosím ověřte individuálně. Vlastní částky lze zadat volně.",
        "settings.hours.1to3": "1 – 3 hodiny",
        "settings.hours.3to6": "3 – 6 hodin",
        "settings.hours.6plus": "6+ hodin",
        "settings.reset": "Obnovit výchozí nastavení",
        "settings.diagnosis": "Diagnostika",
        "settings.feedback": "Zpětná vazba & Podpora",
        "settings.log": "Protokol chyb",
        "settings.info": "Info & Právní",
        "settings.privacy": "Ochrana osobních údajů",
        "settings.help": "Funkce aplikace & Nápověda",
        "settings.imprint": "Impresum",
        "settings.language": "Jazyk",
        "settings.language.section": "Jazyk aplikace",
        "settings.log.empty": "Žádné záznamy.",
        "settings.log.clear": "Smazat protokol?",
        "settings.gps.carplay": "Spustit GPS při připojení CarPlay",
        "settings.gps.carplay.footer": "Automaticky spustí záznam GPS po připojení iPhone k CarPlay.",
        "settings.home.address": "Domácí adresa",
        "settings.home.footer": "Zobrazena jako tlačítko (🏠) ve formuláři jízdy a zvýrazněna v seznamu jízd.",
        "settings.km.label": "Sazba za km",
        "settings.km.legal.footer": "Daňové maximum 2026: 0,38 € / km",
        "settings.chf.rate": "Kurz (EUR = … CHF)",
        "settings.region.inland": "Tuzemsko",
        "settings.region.schweiz": "Švýcarsko (v CHF)",
        "settings.region.ausland": "Zahraničí",
        "settings.meals.values.footer": "Tuzemsko: 0 € · 14 € · 28 €  |  Švýcarsko: 0 · 65 · 65 CHF  |  Zahraničí: 0 € · 10 € · 35 €",
        "settings.mechanic.allowance": "Příplatek montéra",
        "settings.weekend.allowance": "Příplatek za víkend/svátky",
        "settings.hotel.title": "Ubytování/Snídaně",
        "settings.hotel.flat": "Paušál za ubytování",
        "settings.hotel.breakfast": "Paušál za snídani",
        "settings.fuel.type": "Pohon / Typ paliva",
        "settings.fuel.label": "Pohon / Palivo",
        "settings.fuel.consumption.kwh": "Spotřeba (kWh/100 km)",
        "settings.fuel.consumption": "Průměrná spotřeba",
        "settings.fuel.price.electricity": "Výchozí cena elektřiny",
        "settings.fuel.price": "Výchozí cena paliva",
        "settings.privacy.label": "Zásady ochrany osobních údajů",
        "settings.help.label": "Funkce aplikace & Průvodce",
        "settings.mechanic.inland.label": "Příplatek tuzemsko / Německo",
        "settings.mechanic.swiss.label": "Příplatek Švýcarsko / Mimo závod",
        "settings.mechanic.abroad.label": "Příplatek zahraničí / Mimo závod a Německo",
        "settings.weekend.inland.label": "Příplatek tuzemsko / Evropa",
        "settings.weekend.swiss.label": "Příplatek Švýcarsko / Evropa",
        "settings.weekend.abroad.label": "Příplatek zahraničí / Ostatní oblasti",
        "settings.mechanic.footer": "Paušální příplatek: 12 € tuzemsko, 18 CHF Švýcarsko, 50 € zahraničí. Vypláceno přes mzdu, NENÍ součástí náhrad.",
        "settings.weekend.footer": "Paušální denní příplatek tuzemsko/Švýcarsko (60 € / 90 CHF) nebo zahraničí (72 €). Sobota/neděle nebo svátky. NENÍ součástí náhrad.",
        "settings.fuel.footer": "Typ pohonu, cena a spotřeba jsou automaticky vyplněny při přidávání nových jízd.",
        "settings.reset.footer": "Obnoví všechny zákonné výchozí hodnoty dle § 9 EStG.",
        "settings.reset.confirm": "Všechny paušály budou resetovány na zákonné výchozí hodnoty.",
        "settings.backup": "Záloha a obnovení",
        "settings.backup.save.local": "Uložit zálohu lokálně",
        "settings.backup.share": "Sdílet zálohu / exportovat do cloudu",
        "settings.backup.restore": "Obnovit zálohu",
        "settings.backup.saved": "Uložené zálohy",
        "settings.backup.footer": "Uchovává se max. 10 záloh.",
        "settings.delete.all": "Smazat všechny záznamy",
        "settings.delete.footer": "Neodvolatelně smaže všechny záznamy. Nastavení zůstanou zachována.",
        "settings.manage.data": "Správa dat",
        "settings.app.info": "Info o aplikaci a ochrana dat",
        "settings.version": "Verze aplikace",
        "settings.developer": "Vývojář",
        "settings.contact": "Kontakt",
        "settings.log.section": "Protokol a zpětná vazba",
        "settings.log.title": "Protokol aplikace",
        "settings.log.empty.desc": "Protokol je prázdný.",
        "settings.log.show": "Zobrazit protokol",
        "settings.swipe.actions": "Určuje akci a barvu při přejetí doleva nebo doprava.",
        "settings.swipe.delete": "Smazat",
        "settings.swipe.edit": "Upravit",
        "settings.swipe.copy": "Kopírovat",
        "settings.swipe.none": "-",
        "settings.swipe.title": "Gesta přejetí",
        "settings.swipe.left": "Přejeďte vlevo",
        "settings.swipe.right1": "Přejeďte vpravo 1",
        "settings.swipe.right2": "Přejeďte vpravo 2",
        "settings.accessibility": "Usnadnění přístupu",
        "settings.log.delete": "Smazat protokol",
        "settings.log.delete.title": "Smazat protokol?",
        "settings.log.delete.msg": "Protokol bude smazán. Automaticky se obnoví při dalším spuštění aplikace.",
        "settings.log.deleted": "Protokol smazán.",
        "settings.log.mem.note": "Protokol je uložen pouze v paměti a automaticky smazán při dalším spuštění. Neobsahuje osobní údaje.",
        "settings.language.footer": "Aplikace používá jazyk systému iOS. Změna: Nastavení → Obecné → Jazyk a oblast.",
        "settings.delete.confirm": "Tuto akci nelze vrátit zpět. Nejprve vytvořte zálohu.",
        "settings.restore.confirm": "Všechna aktuální data budou nahrazena daty ze zálohy.",
        "settings.delete.all.title": "Smazat všechny záznamy?",
        "settings.delete.all.btn": "Smazat vše",
        "settings.all.deleted": "Všechny záznamy byly smazány.",
        "settings.restore.title": "Obnovit zálohu?",
        "settings.restore.btn": "Načíst zálohu",
        "settings.reset.title": "Obnovit výchozí hodnoty?",
        "settings.reset.btn": "Resetovat",
        "settings.backup.loading": "Načítání záloh…",
        "settings.backup.empty.title": "Žádné zálohy iCloud",
        "settings.backup.empty.hint": "Vytvořte zálohu přes Nastavení → záloha iCloud",
        "settings.backup.saved.title": "Uložené zálohy",
        "settings.backup.restore.btn": "Obnovit",
        "settings.backup.restore.msg": "Všechna data budou nahrazena zálohou z %@.",
        "settings.backup.delete.title": "Smazat zálohu?",
        "settings.scan.receipt": "Skenovat doklad",
        "settings.scan.receipt.hint": "Automatické rozpoznání položek, kategorií a částek",
        "settings.entry.add": "Přidat záznam",

        // Overview
        "overview.ausgaben": "Výdaje",
        "overview.not.reimbursable": "nehradí se",
        "overview.total.ausgaben": "Celkové výdaje",
        "overview.meal.balance": "Saldo stravného",
        "overview.flat.label": "Paušál",
        "overview.fuel": "Palivo / Elektřina",
        "overview.driven.km": "Náklady ujetých km",
        "overview.meal.expenses": "Výdaje na stravování",
        "overview.travel.expenses": "Cestovní výdaje / Vozidlo",
        "overview.private.expenses": "Soukromé výdaje",
        "overview.entry": "Záznam",
        "overview.entries": "Záznamy",
        "overview.no.entries": "Žádné záznamy",

        // Filter
        "filter.woche": "Týden",
        "filter.monat": "Měsíc",
        "filter.jahr": "Rok",

        // Statistik
        "stat.tab.months": "Měsíce",
        "stat.tab.routes": "Trasy",
        "stat.tab.tax": "Daň",
        "stat.reimbursement.per.month": "Náhrada za měsíc",
        "stat.best.month": "Nejlepší měsíc: **%@** s %@",
        "stat.top.routes": "Nejčastější trasy",
        "stat.tax.year": "Daňový rok %@",
        "stat.total.reimbursement": "Celková náhrada %@",
        "stat.tax.annex.n": "Pro Anlage N / vyúčtování cestovních nákladů",
        "stat.mechanic.allowance": "Příplatek montéra %@",
        "stat.payroll.note": "Složka mzdy – není součástí cestovních nákladů (Anlage N)",
        "stat.disclaimer": "Tato analýza slouží jako orientace. Ověřte částky se svým daňovým poradcem.",

        // Summary tiles
        "stat.trips.label": "Jízdy",
        "stat.km.label": "Kilometry",
        "stat.reimbursement.label": "Náhrada",
    ],

    .turkish: [
        // Actions
        "action.add": "Ekle",
        "action.edit": "Düzenle",
        "action.delete": "Sil",
        "action.cancel": "İptal",
        "action.save": "Kaydet",
        "action.done": "Tamam",
        "action.close": "Kapat",

        // Common
        "common.optional": "İsteğe bağlı",
        "common.note": "Not",
        "common.date": "Tarih",
        "common.amount": "Tutar",
        "common.region": "Bölge",

        // Tabs (Tab Bar)
        "tab.trips": "Seyahatler",
        "tab.meals": "Yemek",
        "tab.accommodation": "Konaklama",
        "tab.vehicle": "Araç",
        "tab.overview": "Genel Bakış",
        "tab.fahrten": "Seyahat",
        "tab.arbeitszeit": "Yemek",
        "tab.uebernachtung": "Konaklama",
        "tab.kfz": "Araç",
        "tab.statistik": "İstatistik",
        "tab.search": "Ara",

        // TravelRegion
        "region.inland": "Yurt içi",
        "region.schweiz": "İsviçre",
        "region.ausland": "Yurt dışı",

        // HotelMode
        "hotel.mode.flat": "Sabit ücret",
        "hotel.mode.actual": "Gerçek tutar",

        // VehicleCostCategory
        "vehicle.cat.werkstatt": "Servis / Onarım",
        "vehicle.cat.versicherung": "Sigorta",
        "vehicle.cat.tuev": "Araç muayenesi",
        "vehicle.cat.steuer": "Motorlu taşıt vergisi",
        "vehicle.cat.reifen": "Lastik",
        "vehicle.cat.leasing": "Leasing",
        "vehicle.cat.strom": "Elektrik / Şarj",
        "vehicle.cat.waesche": "Araç yıkama",
        "vehicle.cat.sonstiges": "Diğer",

        // ReisespesenKategorie
        "kfz.cat.werkstatt": "Atölye",
        "kfz.cat.leasing": "Kiralama",
        "kfz.cat.vignette": "Vinyeti / Yol Ücreti",
        "kfz.cat.benzin": "Benzin",
        "kfz.cat.strom": "Elektrik / Şarj",
        "kfz.cat.steuer": "Araç Vergisi",
        "kfz.cat.versicherung": "Araç Sigortası",
        "kfz.cat.verpflegung": "Yemek",
        "kfz.cat.sonstiges": "Diğer",

        // KFZ view strings
        "kfz.title": "Araç Giderleri",
        "kfz.belege": "Fiş",
        "kfz.manual": "Manuel ekle",
        "kfz.scan": "Fiş tara",
        "kfz.scan.hint": "Kamera veya fotoğraf – veriler otomatik olarak tanınır",
        "kfz.empty.title": "Araç Giderleri",
        "kfz.empty.subtitle": "Servis, kiralama, yakıt ve diğer maliyetleri takip edin",
        "kfz.empty.scan": "Tara",
        "kfz.empty.manual": "Manuel",
        "kfz.kategorie": "Kategori",
        "kfz.betrag": "Tutar",
        "kfz.notiz": "Not",
        "kfz.bezeichnung": "Açıklama",
        "kfz.add.first": "İlk girişi ekle",
        "kfz.ausgaben": "Giderler",
        "kfz.netto": "Net",
        "kfz.waesche.title": "Araç Yıkama",
        "kfz.waesche.hint": "Araç yıkama eklemek için + tuşuna basın.",
        "kfz.waesche.gesamt": "Toplam",
        "kfz.standard.kwh": "Ø Varsayılan değeri kullan (0,30 €/kWh)",

        // Overview
        "overview.empty.title": "Veri yok",
        "overview.empty.subtitle": "Seyahat, yemek veya\nkonaklama ekleyin",
        "overview.total": "Toplam geri ödeme",
        "overview.trips.unit": "Seyahat",
        "overview.days.unit": "Gün",
        "overview.nights.unit": "Gece",
        "overview.accommodation.short": "Konaklama",

        // Trips
        "trips.gps.tile": "GPS\nBaşlat",
        "trips.gps.menu": "GPS Kaydı",
        "trips.new.tile": "Yeni\nSeyahat",
        "trips.empty.title": "Seyahat yok",
        "trips.empty.subtitle": "GPS kaydı başlatın veya manuel seyahat ekleyin",
        "trips.all": "Tüm seyahatler",
        "trips.unit": "Seyahat",
        "trips.form.new": "Yeni seyahat",
        "trips.form.edit": "Seyahati düzenle",
        "trips.from": "Nereden",
        "trips.to": "Nereye",
        "trips.km.label": "Kilometre",
        "trips.result": "Sonuç",
        "trips.distance": "Mesafe",
        "trips.rate": "Oran",
        "trips.reimbursement": "Geri ödeme",
        "trips.start": "Başlangıç yeri",
        "trips.destination": "Hedef",
        "trips.route": "Güzergah",
        "trips.navigation.section": "Navigasyon",
        "trips.calculation": "Hesaplama",
        "trips.maps.title": "Harita entegrasyonu",
        "trips.maps.subtitle": "Otomatik güzergah hesaplama · yalnızca Pro",
        "trips.maps.open": "Navigasyonu şununla aç",
        "trips.apple.maps": "Apple Haritalar",
        "trips.google.maps": "Google Haritalar",
        "trips.maps.open.btn": "Haritada aç",
        "trips.auto.label": "Otomatik",
        "trips.auto.hint": "Başlangıç ve hedef girin – km otomatik hesaplanır",
        "trips.auto.calc": "Otomatik hesaplanıyor…",
        "trips.route.computing": "Güzergah otomatik hesaplanıyor…",
        "trips.route.error": "Lütfen başlangıç ve hedefi kontrol edin",
        "trips.live.route": "Canlı güzergah",
        "trips.gps.title": "GPS seyahati",
        "trips.gps.heading": "GPS seyahati kaydet",
        "trips.gps.desc": "Kat edilen mesafe GPS ile ölçülür\nve otomatik aktarılır.",
        "trips.gps.startbtn": "Kaydı başlat",
        "trips.gps.running": "Kayıt devam ediyor",
        "trips.gps.stop": "Seyahati bitir ve aktar",
        "trips.gps.permission": "Konum izni isteniyor…",
        "trips.gps.permission.desc": "Lütfen iletişim kutusunda konum erişimine izin verin.",
        "trips.gps.geocoding": "Adresler belirleniyor…",
        "trips.gps.geocoding.wait": "Bir an lütfen",
        "trips.gps.detected": "GPS seyahati algılandı",
        "trips.gps.detected.desc": "Mesafe, başlangıç ve hedef otomatik belirlendi. Lütfen kontrol edin ve gerekirse düzeltin.",
        "trips.gps.waiting": "GPS bekleniyor…",
        "trips.nav.start": "Navigasyonu başlat",

        // Meals
        "meals.add": "Yemek ekle",
        "meals.add.hint": "Gün eklemek için dokunun",
        "meals.all": "Tüm kayıtlar",
        "meals.unit": "Gün",
        "meals.form.new": "Yeni yemek",
        "meals.form.edit": "Kaydı düzenle",
        "meals.region": "Seyahat bölgesi",
        "meals.absence": "Toplam çalışma süresi",
        "meals.begin": "Başlangıç",
        "meals.end": "Bitiş",
        "meals.result": "Sonuç",
        "meals.absence.label": "Devamsızlık",
        "meals.level": "Seviye",
        "meals.allowance": "Yemek ödeneği",
        "meals.badge.none": "Yok",
        "meals.level.none": "Yok (< 1 s)",
        "meals.level.1": "Seviye 1 (1–3 s)",
        "meals.level.2": "Seviye 2 (3–6 s)",
        "meals.level.3": "Seviye 3 (6+ s)",

        // Accommodation
        "hotel.title": "Konaklamalar",
        "hotel.add": "Konaklama ekle",
        "hotel.add.hint": "Konaklama eklemek için dokunun",
        "hotel.all": "Tüm konaklamalar",
        "hotel.unit": "Gece",
        "hotel.section": "Konaklama",
        "hotel.form.new": "Yeni konaklama",
        "hotel.form.edit": "Konaklamayı düzenle",
        "hotel.city": "Şehir / Konum",
        "hotel.city.placeholder": "örn. İstanbul",
        "hotel.name": "Otel",
        "hotel.billing": "Faturalama yöntemi",
        "hotel.type": "Tür",
        "hotel.cost": "Tutar (€)",
        "hotel.reimbursement": "Geri ödeme",
        "hotel.flat.label": "Konaklama ödeneği",
        "hotel.actual.cost": "Gerçek maliyetler",
        "hotel.flat.badge": "Sabit ücret",
        "hotel.actual.badge": "Gerçek tutar",
        "hotel.info": "Ödenek %@ / gece. Gerçek maliyetler ödeneği aşarsa tam tutar geri ödenir.",
        "hotel.over.flat": "Ödenek üstü (%@)",

        // Vehicle
        "vehicle.title": "Araç giderleri",
        "vehicle.add": "Araç gideri ekle",
        "vehicle.add.hint": "Servis, sigorta veya diğer araç giderleri",
        "vehicle.unit": "Kayıt",
        "vehicle.form.new": "Yeni gider",
        "vehicle.form.edit": "Gideri düzenle",
        "vehicle.category.section": "Kategori",
        "vehicle.details": "Ayrıntılar",
        "vehicle.title.label": "Açıklama",
        "vehicle.mileage": "Kilometre sayacı (km)",
        "vehicle.summary": "Özet",

        // Navigation titles
        "nav.arbeitszeit": "Yemek & Giderler",
        "nav.kfz": "Araç Giderleri",
        "nav.search": "Ara",
        "nav.uebernachtung": "Konaklamalar",
        "nav.trips": "Seyahatler",

        // Misc
        "misc.today": "Bugün",
        "misc.details": "Ayrıntılar",
        "misc.date": "Tarih",
        "misc.optional": "İsteğe bağlı",
        "misc.no.entries": "Kayıt yok",
        "misc.no.entries.period": "Seçilen dönemde kayıt yok",
        "misc.trip.end": "Seyahati bitir",
        "misc.edit": "Düzenle",
        "misc.new": "Yeni",
        "misc.all.trips": "Tüm seyahatler",
        "misc.copy": "Kopyala",
        "misc.send": "Gönder",
        "misc.manage": "Yönet",
        "misc.stop": "Durdur",
        "misc.resume": "Şimdi devam et",
        "misc.end.trip": "Seyahati bitir",
        "misc.recorded.so.far": "şimdiye kadar kaydedildi",
        "misc.paused": "Duraklatıldı",
        "misc.loading": "Yükleniyor…",
        "misc.private": "Özel",
        "misc.business": "İş",
        "misc.no.entries.search": "Kayıt bulunamadı",
        "misc.search.hint": "Bir anahtar kelime girin\nveya tarih seçin",
        "misc.search.hint2": "Farklı bir anahtar kelime\nveya başka bir tarih deneyin",
        "filter.day": "Gün",
        "filter.week": "Hafta",
        "filter.month": "Ay",
        "filter.all": "Tümü",
        "filter.year": "Yıl",
        "arbeitszeit.add.title": "Çalışma günü ekle",
        "arbeitszeit.add.subtitle": "Toplam çalışma süresi ve yemek ödeneği kaydet",
        "arbeitszeit.no.entries": "Seçilen dönemde kayıt yok",
        "arbeitszeit.monteur": "Teknisyen ödeneği (maaş, ayrı)",
        "arbeitszeit.wochenende": "Hafta sonu/tatil ödeneği (maaş, ayrı)",

        // Settings
        "settings.title": "Ayarlar",
        "settings.km.title": "Kilometre geri ödemesi",
        "settings.km.rate": "Km oranı",
        "settings.km.footer": "Vergi azami 2026: 0,38 € / km",
        "settings.meals.title": "Yemek ödenekleri",
        "settings.meals.footer": "Tüm tutarlar serbestçe yapılandırılabilir. 1 saatin altındaki devamsızlık için ödenek her zaman 0 €'dur.",
        "settings.hotel.footer": "Almanya standardı: 20,00 € / gece. Bireysel tutarlar serbest girilebilir.",
        "settings.hours.1to3": "1 – 3 saat",
        "settings.hours.3to6": "3 – 6 saat",
        "settings.hours.6plus": "6+ saat",
        "settings.reset": "Varsayılanlara sıfırla",
        "settings.diagnosis": "Teşhis",
        "settings.feedback": "Geri bildirim & Destek",
        "settings.log": "Hata günlüğü",
        "settings.info": "Bilgi & Yasal",
        "settings.privacy": "Gizlilik",
        "settings.help": "Uygulama özellikleri & Yardım",
        "settings.imprint": "Künye",
        "settings.language": "Dil",
        "settings.language.section": "Uygulama dili",
        "settings.log.empty": "Kayıt yok.",
        "settings.log.clear": "Günlük silinsin mi?",
        "settings.gps.carplay": "CarPlay bağlantısında GPS başlat",
        "settings.gps.carplay.footer": "iPhone CarPlay'e bağlandığında GPS kaydını otomatik başlatır.",
        "settings.home.address": "Ev adresi",
        "settings.home.footer": "Seyahat formunda hızlı erişim butonu (🏠) olarak gösterilir.",
        "settings.km.label": "Km ödeneği",
        "settings.km.legal.footer": "Vergi azami 2026: 0,38 € / km",
        "settings.chf.rate": "Kur (EUR = … CHF)",
        "settings.region.inland": "Yurt içi",
        "settings.region.schweiz": "İsviçre (CHF)",
        "settings.region.ausland": "Yurt dışı",
        "settings.meals.values.footer": "Yurt içi: 0 € · 14 € · 28 €  |  İsviçre: 0 · 65 · 65 CHF  |  Yurt dışı: 0 € · 10 € · 35 €",
        "settings.mechanic.allowance": "Teknisyen ödeneği",
        "settings.weekend.allowance": "Hafta sonu/tatil ödeneği",
        "settings.hotel.title": "Konaklama/Kahvaltı",
        "settings.hotel.flat": "Konaklama ödeneği",
        "settings.hotel.breakfast": "Kahvaltı ödeneği",
        "settings.fuel.type": "Yakıt / Tahrik türü",
        "settings.fuel.label": "Yakıt / Tahrik",
        "settings.fuel.consumption.kwh": "Tüketim (kWh/100 km)",
        "settings.fuel.consumption": "Ortalama tüketim",
        "settings.fuel.price.electricity": "Varsayılan elektrik fiyatı",
        "settings.fuel.price": "Varsayılan yakıt fiyatı",
        "settings.privacy.label": "Gizlilik Politikası",
        "settings.help.label": "Uygulama Özellikleri & Kılavuz",
        "settings.mechanic.inland.label": "Yurt içi / Almanya ödeneği",
        "settings.mechanic.swiss.label": "İsviçre / Tesis dışı ödeneği",
        "settings.mechanic.abroad.label": "Yurt dışı / Tesis ve Almanya dışı ödeneği",
        "settings.weekend.inland.label": "Yurt içi / Avrupa ödeneği",
        "settings.weekend.swiss.label": "İsviçre / Avrupa ödeneği",
        "settings.weekend.abroad.label": "Yurt dışı / Diğer bölgeler ödeneği",
        "settings.mechanic.footer": "Götürü ödenek: €12 yurt içi, 18 CHF İsviçre, €50 yurt dışı. Maaş üzerinden ödenir, geri ödemelere DAHİL DEĞİL.",
        "settings.weekend.footer": "Günlük götürü ödenek yurt içi/İsviçre (€60 / 90 CHF) veya yurt dışı (€72). Cumartesi/Pazar veya tatil günleri. Maaş üzerinden ödenir, geri ödemelere DAHİL DEĞİL.",
        "settings.fuel.footer": "Tahrik türü, fiyat ve tüketim yeni seyahat eklerken otomatik doldurulur.",
        "settings.reset.footer": "§ 9 EStG'ye göre tüm yasal varsayılanları geri yükler.",
        "settings.reset.confirm": "Tüm sabit ücretler yasal varsayılan değerlere sıfırlanacak.",
        "settings.backup": "Yedekleme ve geri yükleme",
        "settings.backup.save.local": "Yerel yedekleme kaydet",
        "settings.backup.share": "Yedekleme paylaş / buluta aktar",
        "settings.backup.restore": "Yedeklemeyi geri yükle",
        "settings.backup.saved": "Kaydedilen yedeklemeler",
        "settings.backup.footer": "En fazla 10 yedekleme saklanır.",
        "settings.delete.all": "Tüm kayıtları sil",
        "settings.delete.footer": "Tüm kayıtları kalıcı olarak siler. Ayarlar korunur.",
        "settings.manage.data": "Verileri yönet",
        "settings.app.info": "Uygulama bilgisi ve gizlilik",
        "settings.version": "Uygulama sürümü",
        "settings.developer": "Geliştirici",
        "settings.contact": "İletişim",
        "settings.log.section": "Günlük ve geri bildirim",
        "settings.log.title": "Uygulama günlüğü",
        "settings.log.empty.desc": "Günlük boş.",
        "settings.log.show": "Günlüğü göster",
        "settings.swipe.actions": "Sola veya sağa kaydırmada görünecek işlemi ve rengi belirler.",
        "settings.swipe.delete": "Sil",
        "settings.swipe.edit": "Düzenle",
        "settings.swipe.copy": "Kopyala",
        "settings.swipe.none": "-",
        "settings.swipe.title": "Kaydırma hareketleri",
        "settings.swipe.left": "Sola kaydır",
        "settings.swipe.right1": "Sağa kaydır 1",
        "settings.swipe.right2": "Sağa kaydır 2",
        "settings.accessibility": "Erişilebilirlik",
        "settings.log.delete": "Günlüğü sil",
        "settings.log.delete.title": "Günlük silinsin mi?",
        "settings.log.delete.msg": "Günlük temizlenecek. Bir sonraki uygulama başlangıcında otomatik olarak yeniden oluşturulacak.",
        "settings.log.deleted": "Günlük silindi.",
        "settings.log.mem.note": "Günlük yalnızca bellekte tutulur ve bir sonraki uygulama başlangıcında otomatik olarak temizlenir. Kişisel veri içermez.",
        "settings.language.footer": "Uygulama iOS sistem dilini kullanır. Değiştirmek için: Ayarlar → Genel → Dil ve Bölge.",
        "settings.delete.confirm": "Bu işlem geri alınamaz. Önce yedek alın.",
        "settings.restore.confirm": "Tüm mevcut veriler yedek verileriyle değiştirilecek.",
        "settings.delete.all.title": "Tüm girişler silinsin mi?",
        "settings.delete.all.btn": "Hepsini sil",
        "settings.all.deleted": "Tüm girişler silindi.",
        "settings.restore.title": "Yedek geri yüklensin mi?",
        "settings.restore.btn": "Yedeği yükle",
        "settings.reset.title": "Varsayılanlar geri yüklensin mi?",
        "settings.reset.btn": "Sıfırla",
        "settings.backup.loading": "Yedekler yükleniyor…",
        "settings.backup.empty.title": "Henüz iCloud yedeği yok",
        "settings.backup.empty.hint": "Ayarlar → iCloud Yedekleme üzerinden yedek oluşturun",
        "settings.backup.saved.title": "Kayıtlı yedekler",
        "settings.backup.restore.btn": "Geri yükle",
        "settings.backup.restore.msg": "Tüm veriler %@ tarihli yedekle değiştirilecek.",
        "settings.backup.delete.title": "Yedek silinsin mi?",
        "settings.scan.receipt": "Fiş tara",
        "settings.scan.receipt.hint": "Kalemleri, kategorileri ve tutarları otomatik tanı",
        "settings.entry.add": "Kayıt ekle",

        // Overview
        "overview.ausgaben": "Harcamalar",
        "overview.not.reimbursable": "geri ödenmiyor",
        "overview.total.ausgaben": "Toplam harcamalar",
        "overview.meal.balance": "Yemek bakiyesi",
        "overview.flat.label": "Ödenek",
        "overview.fuel": "Yakıt / Elektrik",
        "overview.driven.km": "Gidilen km maliyeti",
        "overview.meal.expenses": "Yemek harcamaları",
        "overview.travel.expenses": "Seyahat Giderleri / Araç",
        "overview.private.expenses": "Özel harcamalar",
        "overview.entry": "Kayıt",
        "overview.entries": "Kayıtlar",
        "overview.no.entries": "Kayıt yok",

        // Filter
        "filter.woche": "Hafta",
        "filter.monat": "Ay",
        "filter.jahr": "Yıl",

        // Statistik
        "stat.tab.months": "Aylar",
        "stat.tab.routes": "Güzergahlar",
        "stat.tab.tax": "Vergi",
        "stat.reimbursement.per.month": "Aylık geri ödeme",
        "stat.best.month": "En iyi ay: **%@** – %@",
        "stat.top.routes": "En sık güzergahlar",
        "stat.tax.year": "Vergi yılı %@",
        "stat.total.reimbursement": "Toplam geri ödeme %@",
        "stat.tax.annex.n": "Anlage N / iş seyahati raporu için",
        "stat.mechanic.allowance": "Teknisyen ödeneği %@",
        "stat.payroll.note": "Maaş bileşeni – seyahat giderlerinin parçası değil (Anlage N)",
        "stat.disclaimer": "Bu rapor yalnızca yönlendirme amaçlıdır. Tutarları vergi danışmanınızla doğrulayın.",

        // Summary tiles
        "stat.trips.label": "Seyahatler",
        "stat.km.label": "Kilometre",
        "stat.reimbursement.label": "Geri ödeme",
    ],

]
